### ISSUE TITLE
Get referenced documents when answering

### ISSUE THREAD

**Issue by brunoedcf** [HKUDS/LightRAG#101]
I want to know if when we ask a question in RAG, and it consults a knowledge graph, would it be possible for it to bring, in addition to the answer, which document(s) (of those that were indexed) that it took for reference when answering.

**Comment by LarFii** [comment]
Yes, you can modify the [query function](https://github.com/HKUDS/LightRAG/blob/db5bbcd6a11fd09e1953ffba2336c29221479445/lightrag/operate.py#L877) in `lightrag/operate.py` to return the retrieved content. The variable name for the retrieved content is `context`.
