### ISSUE TITLE
Error: Tokens exceeding the model's max token limit despite manually setting the limit

### ISSUE THREAD

**Issue by venki-lfc** [HKUDS/LightRAG#102]
I hosted the LLM and embedding model locally and I tried to embed the txt file using `rag.insert()`. Here is my embedding and LLM configuration:
```
rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=llm_model_func, llm_model_name="Qwen2.5-72B", llm_model_max_token_size=4096,
    embedding_func=EmbeddingFunc(
        embedding_dim=1024, max_token_size=4096, func=embedding_func
    ),
)

INFO:lightrag:Logger initialized for working directory: ./colpali
DEBUG:lightrag:LightRAG init with param:
  working_dir = ./colpali,
  chunk_token_size = 1200,
  chunk_overlap_token_size = 100,
  tiktoken_model_name = gpt-4o-mini,
  entity_extract_max_gleaning = 1,
  entity_summary_to_max_tokens = 500,
  node_embedding_algorithm = node2vec,
  node2vec_params = {'dimensions': 1536, 'num_walks': 10, 'walk_length': 40, 'window_size': 2, 'iterations': 3, 'random_seed': 3},
  embedding_func = {'embedding_dim': 1024, 'max_token_size': 4096, 'func': <function embedding_func at 0x000002877350F380>},
  embedding_batch_num = 32,
  embedding_func_max_async = 16,
  llm_model_func = <function llm_model_func at 0x000002877350E0C0>,
  llm_model_name = Qwen2.5-72B,
  llm_model_max_token_size = 4096,
  llm_model_max_async = 16,
  key_string_value_json_storage_cls = <class 'lightrag.storage.JsonKVStorage'>,
  vector_db_storage_cls = <class 'lightrag.storage.NanoVectorDBStorage'>,
  vector_db_storage_cls_kwargs = {},
  graph_storage_cls = <class 'lightrag.storage.NetworkXStorage'>,
  enable_llm_cache = True,
  addon_params = {},
  convert_response_to_json_func = <function convert_response_to_json at 0x000002876F114D60>

INFO:lightrag:Load KV full_docs with 0 data
INFO:lightrag:Load KV text_chunks with 0 data
INFO:lightrag:Load KV llm_response_cache with 0 data
INFO:nano-vectordb:Init {'embedding_dim': 1024, 'metric': 'cosine', 'storage_file': './colpali\\vdb_entities.json'} 0 data
INFO:nano-vectordb:Init {'embedding_dim': 1024, 'metric': 'cosine', 'storage_file': './colpali\\vdb_relationships.json'} 0 data
INFO:nano-vectordb:Init {'embedding_dim': 1024, 'metric': 'cosine', 'storage_file': './colpali\\vdb_chunks.json'} 0 data
```

You can clearly see the token size limit is set to 4096 for both the LLM and the embedding model. Now when I insert a txt file, the first few chunks are processed successfully. However, I get error for one of the chunks saying the model's token limit is 8000 (I set it when I host the model using vLLM). 
The success message appears like this:
```
INFO:httpx:HTTP Request: POST http://bba-ai:8004/v1/chat/completions "HTTP/1.1 200 OK"
⠙ Processed 1 chunks, 42 entities(duplicated), 6 relations(duplicated)
INFO:httpx:HTTP Request: POST http://bba-ai:8004/v1/chat/completions "HTTP/1.1 200 OK"
⠹ Processed 2 chunks, 75 entities(duplicated), 26 relations(duplicated)
INFO:httpx:HTTP Request: POST http://bba-ai:8004/v1/chat/completions "HTTP/1.1 200 OK"
⠸ Processed 3 chunks, 104 entities(duplicated), 54 relations(duplicated)
```
And then I get the error:
```
BadRequestError: Error code: 400 - {'object': 'error', 'message': "This model's maximum context length is 8000 tokens. 
However, you requested 8029 tokens in the messages, 
Please reduce the length of the messages.", 'type': 'BadRequestError', 'param': None, 'code': 400}
```
My question is, despite setting the limit to 4096, how does the chunk size exceed 8000? What is going on here? And how do I solve this issue without having to increase the token size limit of the vLLM model?

**Comment by LarFii** [comment]
You can adjust the retrieved token size by modifying the [QueryParam](https://github.com/HKUDS/LightRAG/blob/db5bbcd6a11fd09e1953ffba2336c29221479445/lightrag/base.py#L17C1-L24C44).

**Comment by venki-lfc** [comment]
Thank you for your answer. I see that will solve the issue during `rag.query()`. But my problem happens during `rag.insert()` despite setting the `llm_model_max_token_size=4096`. But somehow during the insertion, the chunk size exceeds 8000. Any way to get around that? Or do I have to host a model having 32K token size?

**Comment by riddlegit** [comment]
Same error here, I tried to add some codes in 'llm_model_func' truncate and keep whole msg under max tokens, then the error gone , the codes would like below:
```
async def llm_model_func(
    prompt, system_prompt=None, history_messages=[], **kwargs
) -> str:
    print(len(encode_string_by_tiktoken(prompt)))
    return await openai_complete_if_cache(
        "your model name",
        prompt,
        system_prompt=system_prompt,
        history_messages=truncate_list_by_token_size(history_messages, 8000-len(encode_string_by_tiktoken(prompt))),
        api_key="your model key",
        base_url="your model url",
        **kwargs,
    )
```

> Thank you for your answer. I see that will solve the issue during `rag.query()`. But my problem happens during `rag.insert()` despite setting the `llm_model_max_token_size=4096`. But somehow during the insertion, the chunk size exceeds 8000. Any way to get around that? Or do I have to host a model having 32K token size?

**Comment by VALilly** [comment]
Hi, 

Im facing the same issue even after truncating the history messages to be within 8k tokens.

openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens, however you requested 11290 tokens (11290 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.", 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by JoshEe00** [comment]
I am facing the same issue as VALilly on 29 Oct 2024, I am unable to change the context length from 8192 tokens.

**Comment by hachihao** [comment]
How do you solve this problem?

**Comment by alex-dinh** [comment]
Ran into this issue today and I found that this works for me. I think it's better to have no message history during entity/relation extraction since the extraction prompt is sent to the LLM every time. ([source code reference](https://github.com/HKUDS/LightRAG/blob/c0f69395c711387a79d9740a8a78f42c0ba3f3f3/lightrag/operate.py#L2072-L2077)) IMO there should be a better guard rail for this like there is for the query.

```
async def llm_model_func(
    prompt, system_prompt=None, history_messages=[], **kwargs
) -> str:
    return await openai_complete_if_cache(
        os.getenv("LLM_MODEL", "LFM2-8B-A1B"),
        prompt,
        system_prompt=system_prompt,
        history_messages=[], # explicitly set to empty array for entity/relation extraction
        api_key="your model key",
        base_url="your model url",
        **kwargs,
    )
```
