### ISSUE TITLE
openaipublic.blob.core.windows.net 443

### ISSUE THREAD

**Issue by EvanSong77** [HKUDS/LightRAG#111]
File /usr/local/lib/python3.10/dist-packages/tiktoken_ext/openai_public.py:92, in o200k_base()
     91 def o200k_base():
---> 92     mergeable_ranks = load_tiktoken_bpe(
     93         "https://openaipublic.blob.core.windows.net/encodings/o200k_base.tiktoken class="ansi-yellow-bg" style="color:rgb(175,0,0)">",
     94         expected_hash="446a9538cb6c348e3516120d7c08b09f57c36495e2acfffe59a5bf8b0cfb1a2d",
     95     )
     96     special_tokens = {
     97         ENDOFTEXT: 199999,
     98         ENDOFPROMPT: 200018,
     99     }
    100     # This regex could be made more efficient

File /usr/local/lib/python3.10/dist-packages/tiktoken/load.py:147, in load_tiktoken_bpe(tiktoken_bpe_file, expected_hash)
    143 def load_tiktoken_bpe(
    144     tiktoken_bpe_file: str, expected_hash: Optional[str] = None
    145 ) -> dict[bytes, int]:
    146     # NB: do not add caching to this function
--> 147     contents = read_file_cached(tiktoken_bpe_file, expected_hash)
    148     return {
    149         base64.b64decode(token): int(rank)
    150         for token, rank in (line.split() for line in contents.splitlines() if line)
    151     }

File /usr/local/lib/python3.10/dist-packages/tiktoken/load.py:64, in read_file_cached(blobpath, expected_hash)
     61     except OSError:
     62         pass
---> 64 contents = read_file(blobpath)
     65 if expected_hash and not check_hash(contents, expected_hash):
     66     raise ValueError(
     67         f"Hash mismatch for data downloaded from {blobpath} (expected {expected_hash}). "
     68         f"This may indicate a corrupted download. Please try again."
     69     )

File /usr/local/lib/python3.10/dist-packages/tiktoken/load.py:25, in read_file(blobpath)
     23         return f.read()
     24 # avoiding blobfile for public files helps avoid auth issues, like MFA prompts
---> 25 resp = requests.get(blobpath)
     26 resp.raise_for_status()
     27 return resp.content

File /usr/local/lib/python3.10/dist-packages/requests/api.py:73, in get(url, params, **kwargs)
     62 def get(url, params=None, **kwargs):
     63     r"""Sends a GET request.
     64 
     65     :param url: URL for the new :class:`Request` object.
   (...)
     70     :rtype: requests.Response
     71     """
---> 73     return request("get", url, params=params, **kwargs)

File /usr/local/lib/python3.10/dist-packages/requests/api.py:59, in request(method, url, **kwargs)
     55 # By using the 'with' statement we are sure the session is closed, thus we
     56 # avoid leaving sockets open which can trigger a ResourceWarning in some
     57 # cases, and look like a memory leak in others.
     58 with sessions.Session() as session:
---> 59     return session.request(method=method, url=url, **kwargs)

File /usr/local/lib/python3.10/dist-packages/requests/sessions.py:589, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    584 send_kwargs = {
    585     "timeout": timeout,
    586     "allow_redirects": allow_redirects,
    587 }
    588 send_kwargs.update(settings)
--> 589 resp = self.send(prep, **send_kwargs)
    591 return resp

File /usr/local/lib/python3.10/dist-packages/requests/sessions.py:703, in Session.send(self, request, **kwargs)
    700 start = preferred_clock()
    702 # Send the request
--> 703 r = adapter.send(request, **kwargs)
    705 # Total elapsed time of the request (approximately)
    706 elapsed = preferred_clock() - start

File /usr/local/lib/python3.10/dist-packages/requests/adapters.py:688, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    685 if isinstance(e.reason, ConnectTimeoutError):
    686     # TODO: Remove this in 3.0.0: see #2811
    687     if not isinstance(e.reason, NewConnectionError):
--> 688         raise ConnectTimeout(e, request=request)
    690 if isinstance(e.reason, ResponseError):
    691     raise RetryError(e, request=request)

ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/o200k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9b3aa90700>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))

LLM跟embedding模型内部api，试了是OK的，由于是内部网络，外网无法访问，请问这里有没有其他解决方案

**Comment by LarFii** [comment]
可以使用一些本地模型作为替代
