### ISSUE TITLE
Demo `lightrag_ollama_demo` do not work; circular import error

### ISSUE THREAD

**Issue by eliranwong** [HKUDS/LightRAG#113]
I install lightrag-hku by running `pip install lightrag-hku`

I tried to run your example: https://github.com/HKUDS/LightRAG/blob/main/examples/lightrag_ollama_demo.py

I got the circular import error

```
Traceback (most recent call last):
  File "/home/ubuntu/eliran/dev/toolmate/package/toolmate/lightrag.py", line 3, in <module>
    from lightrag import LightRAG, QueryParam
  File "/home/ubuntu/eliran/dev/toolmate/package/toolmate/lightrag.py", line 3, in <module>
    from lightrag import LightRAG, QueryParam
ImportError: cannot import name 'LightRAG' from partially initialized module 'lightrag' (most likely due to a circular import) (/home/ubuntu/eliran/dev/toolmate/package/toolmate/lightrag.py)
```

**Comment by jolocity** [comment]
I had this problem.  It was resolved by creating a new environment using conda.  Then ran the setup.

conda create -n lightrag_new python=3.11
conda activate lightrag_new
github clone <url>
<change dir to clone>
pip install -e .

Hope this helps.

**Comment by Keee-L** [comment]
Perhaps you should rename the Python file, as the lightrag file is conflicting with the lightrag module.
hope this can help you

**Comment by eliranwong** [comment]
> Perhaps you should rename the Python file, as the lightrag file is conflicting with the lightrag module. hope this can help you

Thanks, this was the reason causing the error.  It is now sorted, thanks.  closing now.
