### ISSUE TITLE
ERROR:There is a problem in the running results

### ISSUE THREAD

**Issue by WinstonCHEN1** [HKUDS/LightRAG#115]
在运行完reproduce/Step3_openai_compatible.py之后，得到的结果全部都是error，报错如下：
"error": "too many values to unpack (expected 2)"
模型使用Upstage的solar-mini和solar-embedding-1-large-query
查询中的Log如下图：
![QQ_1729701712421](https://github.com/user-attachments/assets/fd47a045-639f-48f9-9822-c89e9b8265c8)
请问原因是什么？前面的步骤已经跑通了,Graph建起来了。
此外，是否可以使用ChatGLM4-9B-Chat和m3e作为LLM和嵌入模型？

**Comment by TianyuFan0504** [comment]
能给出具体的报错信息吗？具体是在哪里报错的？

我们没有测试过ChatGLM4-9B-Chat，但是根据我们测试其他1B 3B 4B 8B 模型的经验，这个量级的模型性能可能不足以支持复杂查询，提取到的实体种类也不够多，推荐使用14B以上的模型，最好是70B以上的。

**Comment by WinstonCHEN1** [comment]
使用Step_3_openai_compatible.py时，用Upstage平台的solar-mini和solar-embedding-1-large-query模型。
运行的时间似乎是正常的，一个query几十秒左右。
跑出来的结果error.json中都是这样：
![image](https://github.com/user-attachments/assets/b22d7f0f-ee8b-4181-b320-2f183ed3e9b3)

**Comment by LarFii** [comment]
我刚刚修复好了这个bug，可以拉取新的代码再次尝试

**Comment by WinstonCHEN1** [comment]
> 我刚刚修复好了这个bug，可以拉取新的代码再次尝试

问题已解决。感谢🙏

**Comment by WinstonCHEN1** [comment]
@LarFii 在转为使用openai的API，也就是Step_3.py时又出现了同样的问题。报错相同

**Comment by WinstonCHEN1** [comment]
在使用相同的方法修改了代码之后，已经解决。
