### ISSUE TITLE
How to construct the Overall Performance Table in example/batch_eval.py?

### ISSUE THREAD

**Issue by SetonLiang** [HKUDS/LightRAG#124]
How to get the score in Overall Performance Table by running example/batch_eval.py?
1. How are the **result_files** obtained? Are they obtained by querying different classes (in reproduce/Step_3.py)?
2. Why is it unnecessary to consider the **retrieval context** and **ground truth** ? And what's the ground_truth of the generated queries?

**Comment by SetonLiang** [comment]
Got it. So, should I understand that instead of considering the ground truth, the approach is to compare different answers across multiple dimensions and then calculate the win rate, using only the **document content without (query, answer) pairs** in the UltraDomain Benchmark dataset during evaluation?

**Comment by LarFii** [comment]
You're correct. Our approach focuses on evaluating model performance across multiple dimensions. This method directly follows the GraphRAG.
