### ISSUE TITLE
UltraDomain Benchmark

### ISSUE THREAD

**Issue by guanzy2012** [HKUDS/LightRAG#126]
how to use UltraDomain Benchmark

**Comment by SetonLiang** [comment]
need to download the dataset

**Comment by guanzy2012** [comment]
I have got the raw data，could you mind share the demo on how to use it, thank you!

**Comment by LarFii** [comment]
You can follow the [steps](https://github.com/HKUDS/LightRAG#reproduce).

**Comment by guanzy2012** [comment]
Thank you very much！

**Comment by Tejaswgupta** [comment]
@guanzy2012 can you please provide the results if you were able to successfully run it?

**Comment by VasaniDhwanil** [comment]
Hi @guanzy2012 ,

i am trying to replicate the paper and was wondering where you got the data from (the 428 textbooks they have used).
