### ISSUE TITLE
Adding 100vh to the visualization code feels better

### ISSUE THREAD

**Issue by saltyfish-kiri** [HKUDS/LightRAG#127]
import networkx as nx
from pyvis.network import Network
import random

G = nx.read_graphml('./test_ollama_t2/graph_chunk_entity_relation.graphml')

net = Network(height="100vh", notebook=True)

net.from_nx(G)

for node in net.nodes:
    node['color'] = "#{:06x}".format(random.randint(0, 0xFFFFFF))

net.show('knowledge_graph.html')

Now it can be displayed in full screen

**Comment by LarFii** [comment]
Thanks!
