### ISSUE TITLE
Rate limit exceeding 

### ISSUE THREAD

**Issue by NIHALPATTANSHETTY** [HKUDS/LightRAG#128]
I have 3 text files, each about 70 chunks in size, initially I gave all 3 in the input folder, it is saying open ai rate limit exceeded, I tried changing the max llm sync and embedding async, it is not working, I also tried increasing the retries and stop time, it didn't work, I reduced the entities count, It didn't work , finally split each original file into 2 files and tried incremental update, it is failing. 

GrapghRag from Microsoft took all 3 files with all the entities and it is working.

**Comment by sebeyza00** [comment]
hey! had the same error, has to do with the @retry mechanism in llm.py for openai_complete_if_cache(), change the wait parameter to wait=wait_fixed(10), add wait_fixed to tenacity's imports at the top, and this should wait 10 seconds to send the request again after it fails and that should work depending on your openai api rate limits.

**Comment by zcstarr** [comment]
@sebeyza00 this is definitely the patch rather, also to note the retry decorator on the other completes will benefit for wait_fixed(10) as well as I've confirmed it for the decorators for bedrock.

**Comment by NIHALPATTANSHETTY** [comment]
@sebeyza00  Actually in the llm.py file I replaced all instances of the wait exponential with wait fixed and kept it to 180 but it is still failing instantly, why is it so, do I need to make any changes to the example file as well?

**Comment by zcstarr** [comment]
> @sebeyza00 Actually in the llm.py file I replaced all instances of the wait exponential with wait fixed and kept it to 180 but it is still failing instantly, why is it so, do I need to make any changes to the example file as well?

Yeah I think I still hit a concurrency issue, which might need some further investigating, but that's mostly because my request limit is super low, so I need a way to tune the concurrency down to avoid 429s

**Comment by zcstarr** [comment]
Actually dug a bit more into concurrency you might need to set   @NIHALPATTANSHETTY   `llm_model_max_async=4` parameter
example:
```python
rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=bedrock_complete,
    llm_model_max_async=4,
    llm_model_name="Anthropic Claude 3 Haiku // Amazon Bedrock",
    embedding_func=EmbeddingFunc(
        embedding_dim=1024, max_token_size=8192, func=bedrock_embedding
    ),
)
```

**Comment by includingThis** [comment]
> hey! had the same error, has to do with the @Retry mechanism in llm.py for openai_complete_if_cache(), change the wait parameter to wait=wait_fixed(10), add wait_fixed to tenacity's imports at the top, and this should wait 10 seconds to send the request again after it fails and that should work depending on your openai api rate limits.

Thanks, this really made my day. Perhaps this setting might be included in the official code as well?
