### ISSUE TITLE
pip package of lightrag is out of date v0.10-beta.6 does not export LightRAG

### ISSUE THREAD

**Issue by richtong** [HKUDS/LightRAG#13]
I think you need to rerun the pypi packages, when I did a `pip install lightrag-hkd` I get an old package. Looking at your __init__.py up there I see:

```
__version__ = "0.1.0-beta.6"
```

And no exports, you might want to fix. I haven't tried the local usage, but nice to have pypi package :-)

**Comment by LarFii** [comment]
Thank you very much for your attention! It seems the issue occurred because `pip install lightrag-hkd` was used instead of the correct `lightrag-hku`. There's also a deprecated project on PyPI called LightRAG, which might have caused further confusion.
