### ISSUE TITLE
An error occurred: openai_embedding() got an unexpected keyword argument 'model'

### ISSUE THREAD

**Issue by tspp520** [HKUDS/LightRAG#131]
新版本里，在 examples/lightrag_openai_compatible_demo.py，embedding_func配置如下：
async def embedding_func(texts: list[str]) -> np.ndarray:
    return await openai_embedding(
        texts,
        model="text-embedding-3-small",
        api_key="sk-YSJB9R5F9jxBSeSAZve1QVzzCoE14MaPVciMCvAhXx",
        base_url="https://api.agicto.cn/v1",
    )
    但是 vscode一运行就报错：
    (base) ubuntu@ubun:/data1/RcBase/LightRAG20241025/LightRAG$  cd /data1/RcBase/LightRAG20241025/LightRAG ; /usr/bin/env /home/ubuntu/miniconda3/envs/graphrag-ollama-local/bin/python /home/ubuntu/.vscode-server/extensions/ms-python.debugpy-2024.12.0/bundled/libs/debugpy/adapter/../../debugpy/launcher 60437 -- /data1/RcBase/LightRAG20241025/LightRAG/examples/lightrag_openai_compatible_demo.py 
An error occurred: openai_embedding() got an unexpected keyword argument 'model'

怎么也解决不了？大佬们能解释一下吗？
它这个免费，在线的 嵌入模型 到底要怎么配置到embedding_func里？反正折腾了一晚上，都没成功

**Comment by Dormiveglia-elf** [comment]
Try to remove the `model` parameter?(though default is also "text-embedding-3-small") If still not working, I think it is the problem of the "free" embedding model.
