### ISSUE TITLE
There is a typo:"knwoledge"

### ISSUE THREAD

**Issue by crossir79** [HKUDS/LightRAG#132]
async def extract_entities(
    chunks: dict[str, TextChunkSchema],
    knwoledge_graph_inst: BaseGraphStorage,
    entity_vdb: BaseVectorStorage,
    relationships_vdb: BaseVectorStorage,
    global_config: dict,
There is a typo:"knwoledge"

**Comment by Dormiveglia-elf** [comment]
Please refer to PR #123 
Remember to pull the latest code every day.
