### ISSUE TITLE
TypeError: extract_entities() got an unexpected keyword argument 'knowledge_graph_inst'

### ISSUE THREAD

**Issue by ChengyinLee** [HKUDS/LightRAG#133]
After installation, run `lightrag_hf_demo.py`, TypeError: extract_entities() got an unexpected keyword argument 'knowledge_graph_inst' occurs

**Comment by crossir79** [comment]
There is a typo:"knwoledge" #132

**Comment by ChengyinLee** [comment]
Thanks

**Comment by Dormiveglia-elf** [comment]
Refer to PR #123 
Remember to pull the latest code every day.
