### ISSUE TITLE
Incremental update not working

### ISSUE THREAD

**Issue by NIHALPATTANSHETTY** [HKUDS/LightRAG#136]
When I run on single text file with the azure OpenAI instance it is working, I set the azure variables like endpoint, url etc in the example file itself, but when I run incremental update, it throws Set open ai api key error?

**Comment by LarFii** [comment]
I’ll need to see the specific code and logs to analyze the issue.

**Comment by NIHALPATTANSHETTY** [comment]
File "C:\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\e191866\AppData\Roaming\Python\Python312\site-packages\tenacity\asyncio\__init__.py", line 114, in __call__    
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e191866\Downloads\NCG_project\search_team\LightRAG\lightrag\llm.py", line 418, in openai_embedding
    AsyncOpenAI() if base_url is None else AsyncOpenAI(base_url=base_url)
    ^^^^^^^^^^^^^
  File "C:\Users\e191866\AppData\Roaming\Python\Python312\site-packages\openai\_client.py", line 319, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

Btw, I am using Azure open AI instance, when I run initially, even though it gives rate limit after some time, it progresses through the entity extraction phase, but for incremental update, this error is given

**Comment by NIHALPATTANSHETTY** [comment]
Actually, when you try incremental update in the same for loop, it works, but when you try incremental update with the rag instance, rag = LightRAG(working_dir="./dickens")
without specifying the LLM model and the embedding function like you do in the previous step, it throws the OPEN AI key not found error, so better to write 
rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=llm_model_func,
    embedding_func=EmbeddingFunc(
        embedding_dim=embedding_dimension,
        max_token_size=8192,
        func=embedding_func,
    ),
)
, this takes the existing rag instance, with all the previous indexing and runs incremental update properly

**Comment by LarFii** [comment]
I'll fix thesr issues ASAP.
