### ISSUE TITLE
Referencing source documents

### ISSUE THREAD

**Issue by yusufyesil** [HKUDS/LightRAG#137]
Is it possible to reference source documents that are used in retrieval?

**Comment by aiproductguy** [comment]
I added a system prompt and instructions to do this exact thing in the streamlit app, but it needs to index additional data and additional prompt engineering.

Let me know what you think.

Demo: https://lightrag.streamlit.app
PR: https://github.com/HKUDS/LightRAG/pull/139

**Comment by yusufyesil** [comment]
That's great but not what I looking for, I need to give references to which sources used in response.

**Comment by aiproductguy** [comment]
Please share what you find. I am thinking of chaining another agent with source-only kg to verify context and sources. LightRAG's current data model looks like an elegant start, but not yet optimized for a domain-specific problem yet.

**Comment by Dormiveglia-elf** [comment]
Yes, it is possible for sure. I am trying on that, and trying to visualize the query related relations when do the query.

**Comment by yusufyesil** [comment]
Great, I am looking for a workaround to list source docs. Thank you.

**Comment by Tint0ri** [comment]
This is a important feature for retrieval system. According to the source code, only text was upserted into vdb, no relative metadata. For nano_vectordb, upsert does support content with metadata. for query, if content_only is false, a list of Document should be return instead of content only.
