### ISSUE TITLE
example中的batch_eval.py只会返回请求体，不返回结果

### ISSUE THREAD

**Issue by WinstonCHEN1** [HKUDS/LightRAG#153]
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/6a9da2d9-877d-4575-94a2-3fd260608187">
如图，设置好openai的key之后，jsonl文件中只会返回请求体。
已设置result和query的路径，生成文件如图，应该是正常的：
<img width="1093" alt="image" src="https://github.com/user-attachments/assets/36e34f27-0a78-40bd-b84b-8a627af83ad8">
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/c44a7e15-f60e-4b5c-9755-cb82c019cf58">
batch_eval.py文件除了设置key还需要设置什么吗？还是说程序有问题？

**Comment by LarFii** [comment]
结果会存在https://platform.openai.com/batches上面，可以参考openai的batch eval文档

**Comment by WinstonCHEN1** [comment]
> 结果会存在 https://platform.openai.com/batches 上面，可以参考openai的batch eval文档

感谢 已解决

**Comment by WinstonCHEN1** [comment]
> 结果会存在 https://platform.openai.com/batches 上面，可以参考openai的batch eval文档

感谢 已解决
