### ISSUE TITLE
'LightRAG.ainsert' was never awaited

### ISSUE THREAD

**Issue by gujiachun** [HKUDS/LightRAG#154]
An error occurred: This event loop is already running
LightRAG-main\examples\lightrag_openai_compatible_demo.py:107: RuntimeWarning: coroutine 'LightRAG.ainsert' was never awaited
  print(f"An error occurred: {e}")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by Sweewangyu** [comment]
hey，How did you solve it？

**Comment by gujiachun** [comment]
以收到

**Comment by small122** [comment]
咋解决的哥

**Comment by small122** [comment]
> [Sweewangyu](/Sweewangyu)

hey，did you solve it？
