### ISSUE TITLE
Any plan to support deleting or updating existing nodes?

### ISSUE THREAD

**Issue by hejingkan2005** [HKUDS/LightRAG#155]
It's great to know LightRAG supports incremental updates now, which is not supported by GraphRAG. However, we do really need to support modifying, deleting nodes, do you have any plan to support this in upcoming future?

**Comment by LarFii** [comment]
We do have plans to support this feature, but we haven't yet decided on the approach. It could either be based on the original text or involve directly deleting nodes, which might be easier.

**Comment by yilanhu** [comment]
Thank you @LarFii for the reply! We're also interested in how to solve the issue: LLM can generate different nodes/relationships every time even for the same text.

**Comment by nikhilmaddirala** [comment]
> We do have plans to support this feature, but we haven't yet decided on the approach. It could either be based on the original text or involve directly deleting nodes, which might be easier.

I'd love to see support for deleting documents from the input file directly. Deleting nodes and/or relationships would be too complicated for users. Similar to `rag.insert(doc)` it would be great to have something like `rag.delete(doc)` which would automatically update the nodes and relationships.

This would also unlock editing documents by simply doing `rag.delete(old_doc)` and `rag.insert(updated_doc)`

**Comment by LarFii** [comment]
> I'd love to see support for deleting documents from the input file directly. Deleting nodes and/or relationships would be too complicated for users. Similar to `rag.insert(doc)` it would be great to have something like `rag.delete(doc)` which would automatically update the nodes and relationships.
> 
> This would also unlock editing documents by simply doing `rag.delete(old_doc)` and `rag.insert(updated_doc)`

These features are currently in our plan, and our next updates will focus on document deletion and improved update mechanisms.

**Comment by Pranesh026** [comment]
> These features are currently in our plan, and our next updates will focus on document deletion and improved update mechanisms.

Hi , the rag.delete_by_entity("entity_name") is not working properly, When I try to run it, the full graph got deleted. Please let me know, if something I am missing out?
