### ISSUE TITLE
local_query: "IndexError: list index out of range"

### ISSUE THREAD

**Issue by mchzimm** [HKUDS/LightRAG#157]
lib/python3.11/site-packages/lightrag/operate.py", line 404, in local_query
    result = '{' + result.split('{')[1].split('}')[0] + '}'
                   ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by LarFii** [comment]
You might want to check the content of `result`. It's likely that the LLM didn't output in JSON format.

**Comment by mchzimm** [comment]
`result` - is that a file? because i don't see one in the prj root or in WORKING_DIR folder

**Comment by LarFii** [comment]
I mean you can check the content of the `result` variable to see if the LLM's output format is correct.
