### ISSUE TITLE
chronological context (storing and recalling of events)

### ISSUE THREAD

**Issue by mchzimm** [HKUDS/LightRAG#158]
when asking to describe how events developed that are related to a specific theme, they are returned out of order, which also changes (confuses) the context of how they are being represented.

related to that, newer (more recent) relationships should override older ones:
marriage spouse1 -> divorce -> marriage spouse2 -> what's spouse's name?

same also for if there's no chronological data related to context, such as training data for model ("knowledge") should always be considered as "last resort" if there is no data with chronological association.

i've for example ingested a short novel that is divided up into numbered chapters (consecutively number w/ single word as chapter title); i've ingested each chapter separately and in order, and i've added the chapter number and title (word) at the start each time; yet when queried for the main events and how they influenced the story progression, the order of the events were all over the place, creating illogical outcomes (progression / story flow).

**Comment by LarFii** [comment]
This is indeed one of the issues we plan to address in the future. Currently, the indexing phase does not incorporate chronological data, and we're working on figuring out how to effectively integrate chronological order into the system.

**Comment by mchzimm** [comment]
> This is indeed one of the issues we plan to address in the future. Currently, the indexing phase does not incorporate chronological data, and we're working on figuring out how to effectively integrate chronological order into the system.

it seems they've done it: https://help.getzep.com/graphiti/graphiti/overview
