### ISSUE TITLE
[Bug] 项目不能正常调用本地ollama embedding端点，本地接口正常

### ISSUE THREAD

**Issue by zydmtaichi** [HKUDS/LightRAG#162]
the endpoint `http://127.0.0.1:11434/api/embeddings` is good per postman test and script by using ollama lib. However, it malfunctions in lightrag with same logic in [llm.py](https://github.com/HKUDS/LightRAG/blob/main/lightrag/llm.py#L709), pls check and fix this bug
```
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/embeddings "HTTP/1.1 500 Internal Server Error"
INFO:lightrag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
  File "f:\lragtest\ollamalight.py", line 26, in <module>
    rag.insert(f.read())
  File "f:\lightrag\lightrag\lightrag.py", line 162, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "E:\anaconda\envs\lightrag\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "f:\lightrag\lightrag\lightrag.py", line 206, in ainsert
    await self.chunks_vdb.upsert(inserting_chunks)
  File "f:\lightrag\lightrag\storage.py", line 92, in upsert
    embeddings_list = await asyncio.gather(
  File "f:\lightrag\lightrag\utils.py", line 87, in wait_func
    result = await func(*args, **kwargs)
  File "f:\lightrag\lightrag\utils.py", line 43, in __call__
    return await self.func(*args, **kwargs)
  File "f:\lightrag\lightrag\llm.py", line 706, in ollama_embedding
    data = ollama.embeddings(model=embed_model, prompt=text)
  File "E:\anaconda\envs\lightrag\lib\site-packages\ollama\_client.py", line 281, in embeddings
    return self._request(
  File "E:\anaconda\envs\lightrag\lib\site-packages\ollama\_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: failed to generate embedding
```

**Comment by zydmtaichi** [comment]
@LarFii

**Comment by banianzr** [comment]
Maybe this DEBUG INFO indicates sth....
`DEBUG:lightrag:LightRAG init with param:
  working_dir = ./dickens,
  chunk_token_size = 1200,
  chunk_overlap_token_size = 100,
  tiktoken_model_name = gpt-4o-mini,
  entity_extract_max_gleaning = 1,
  entity_summary_to_max_tokens = 500,
  node_embedding_algorithm = node2vec,
  node2vec_params = {'dimensions': 1536, 'num_walks': 10, 'walk_length': 40, 'window_size': 2, 'iterations': 3, 'random_seed': 3},
  embedding_func = {'embedding_dim': 768, 'max_token_size': 8192, 'func': <function <lambda> at 0x10282fd90>},
  embedding_batch_num = 32,
  embedding_func_max_async = 16,
  llm_model_func = <function ollama_model_complete at 0x12d4fa5f0>,
  llm_model_name = qwen2.5:latest,
  llm_model_max_token_size = 32768,
  llm_model_max_async = 4,
  llm_model_kwargs = {'host': 'http://localhost:11434', 'options': {'num_ctx': 32768}},
  key_string_value_json_storage_cls = <class 'lightrag.storage.JsonKVStorage'>,
  vector_db_storage_cls = <class 'lightrag.storage.NanoVectorDBStorage'>,
  vector_db_storage_cls_kwargs = {},
  graph_storage_cls = <class 'lightrag.storage.NetworkXStorage'>,
  enable_llm_cache = True,
  addon_params = {},
  convert_response_to_json_func = <function convert_response_to_json at 0x12d4df880>`

**Comment by zydmtaichi** [comment]
add some debug info below:

ollama version: 0.3.14
conda env with python=3.10
all python libs is installed by `pip install -e .` via requirements.txt

the problem occurs when setting the embedding model to `milkey/gte:large-zh-f16` and embedding_dim to 1024.

the ollama logs about this error pasted below:
```
llama_new_context_with_model: graph splits = 2
INFO [wmain] model loaded | tid="12988" timestamp=1730188832
time=2024-10-29T16:00:32.107+08:00 level=INFO source=server.go:626 msg="llama runner started in 0.51 seconds"
C:\a\ollama\ollama\llm\llama.cpp\ggml\src\ggml.c:13289: GGML_ASSERT(i01 >= 0 && i01 < ne01) failed
time=2024-10-29T16:00:34.902+08:00 level=INFO source=routes.go:478 msg="embedding generation failed: do embedding request: Post \"http://127.0.0.1:54136/embedding\": read tcp 127.0.0.1:54138->127.0.0.1:54136: wsarecv: An existing connection was forcibly closed by the remote host."
[GIN] 2024/10/29 - 16:00:34 | 500 |    3.3720226s |       127.0.0.1 | POST     "/api/embeddings"
```

**Comment by LarFii** [comment]
This issue has already been mentioned in [Ollama](https://github.com/ollama/ollama/issues/7288). Reducing the chunk size might help resolve it.

**Comment by mokby** [comment]
一样的问题，目前还没有好的解决方案
