### ISSUE TITLE
RuntimeWarning: coroutine 'LightRAG.ainsert' was never awaited   print(f"An error occurred: {e}") 

### ISSUE THREAD

**Issue by small122** [HKUDS/LightRAG#163]
运行lightrag_openai_compatible_demo.py报错

**Comment by Dormiveglia-elf** [comment]
Please refer my PR #168 , I think you can run without error now.

**Comment by small122** [comment]
> Please refer my PR #168 , I think you can run the program smoothly without error now.

thank you，i get it
