### ISSUE TITLE
I am trying to use huggingface for llm model and embeddings but ending up with connectivity error for tiktoken.

### ISSUE THREAD

**Issue by msinha251** [HKUDS/LightRAG#166]
Hi Team, I am currently using huggingface llm model and embeddings, it's working fine, but when i am trying to deploy it on interned closed environment, it's haning with below error. 

Error:
`"detail": "HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Read timed out. (read timeout=None)"
`

I am bit confused here, llm and embeddings are pretty fine wrt to connectivity but can someone please help to understand for what exactly reason we are using the tiktoken model and is it possible to completly avoid it ?

**Comment by msinha251** [comment]
Fixed it but locally downloading it and using it with tiktoken cache.

**Comment by Lyrics-WangKL** [comment]
Hello, I had the same problem as you. Also locally download the o200k_base.tiktoken file. But I dont know how to use it wit tiktoken cache. Can you introduce the details? @msinha251 Thx~
