### ISSUE TITLE
Extremely slow indexing even with llama3.2:1b Q8 from Ollama

### ISSUE THREAD

**Issue by Jaykumaran** [HKUDS/LightRAG#174]
Hi Team,

I'm trying to run the ollama_demo.py with dickens file. Im using llama3.2:!b with Q8.

However after the logs of enitity extraction of my 42 chunks is done, there are no further logs whats happening and i'm at what stage. I'm waiting more than half an hour and things are extremely slow.

Hardware: RTX 4050 occupies 5.3GB, i5.

Dissatisfied with its slowness.

I was more positive about this project before starting setting up locally. But now !

If things are this slow even for 1b model, how would we even test qualitative resulst with local models.

**Comment by Jaykumaran** [comment]
My Logs:

`(torch_2x) jaykumaran@Jay:~/Office/LightRAG/examples$ python lightrag_ollama_demo.py
INFO:lightrag:Logger initialized for working directory: ./dickens
DEBUG:lightrag:LightRAG init with param:
  working_dir = ./dickens,
  chunk_token_size = 1200,
  chunk_overlap_token_size = 100,
  tiktoken_model_name = gpt-4o-mini,
  entity_extract_max_gleaning = 1,
  entity_summary_to_max_tokens = 500,
  node_embedding_algorithm = node2vec,
  node2vec_params = {'dimensions': 1536, 'num_walks': 10, 'walk_length': 40, 'window_size': 2, 'iterations': 3, 'random_seed': 3},
  embedding_func = {'embedding_dim': 768, 'max_token_size': 8192, 'func': <function <lambda> at 0x79b9ff30fd90>},
  embedding_batch_num = 32,
  embedding_func_max_async = 16,
  llm_model_func = <function ollama_model_complete at 0x79b9dca196c0>,
  llm_model_name = llama3.2:1b,
  llm_model_max_token_size = 32768,
  llm_model_max_async = 4,
  llm_model_kwargs = {'host': 'http://localhost:11434', 'options': {'num_ctx': 32768}},
  key_string_value_json_storage_cls = <class 'lightrag.storage.JsonKVStorage'>,
  vector_db_storage_cls = <class 'lightrag.storage.NanoVectorDBStorage'>,
  vector_db_storage_cls_kwargs = {},
  graph_storage_cls = <class 'lightrag.storage.NetworkXStorage'>,
  enable_llm_cache = True,
  addon_params = {},
  convert_response_to_json_func = <function convert_response_to_json at 0x79b9dca06830>

INFO:lightrag:Load KV full_docs with 0 data
INFO:lightrag:Load KV text_chunks with 0 data
INFO:lightrag:Load KV llm_response_cache with 0 data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './dickens/vdb_entities.json'} 0 data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './dickens/vdb_relationships.json'} 0 data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './dickens/vdb_chunks.json'} 0 data
INFO:lightrag:Creating a new event loop in a sub-thread.
INFO:lightrag:[New Docs] inserting 1 docs
INFO:lightrag:[New Chunks] inserting 42 chunks
INFO:lightrag:Inserting 42 vectors to chunks
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:lightrag:[Entity Extraction]...
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
`

**Comment by Jaykumaran** [comment]
The main problem is i couldn't infer what's happening bts after entity extraction, my GPU is still running when ollama ps.

**Comment by LarFii** [comment]
This is not a typical issue, and we haven't encountered this situation before. However, it's possible that the 1b model may struggle to extract any meaningful information. You might try using a larger model—trust me, it won't be this slow.

**Comment by Jaykumaran** [comment]
Hello,

I’ve tried using gemma2:2b, and it works as expected. However, it would be helpful if a note regarding this could be added as a comment within the script or in the README section—specifically addressing any issues related to working with llama3.2:1b with Ollama.

**Comment by ASAD-BE18** [comment]
I am having the issue when I tried LightRAG on kaggle

**Comment by ASAD-BE18** [comment]
I have tried with various models, 1B, 7B, 13B but all are very slow.

**Comment by Jaykumaran** [comment]
Hello,

gemma2:2b and qwen2.5:7b works fine in my case when tried locally on RTX3080Ti. However it takes like around 15-20 minutes for Charles Dickens sample book given in the demo.

**Comment by ASAD-BE18** [comment]
Can you please share the specific settings (for LightRAG) that you used?

**Comment by Jaykumaran** [comment]
The main step is to ensure the Ollama model runs continuously, as the Ollama service is set to automatically stop if there are no requests for 5 minutes. Occasionally, some chunks and processes take more than 5 minutes, and it's undesirable for the service to be killed, as this can lead to a delay in API requests and halt further processing.

To prevent this, open a new terminal and run: (recommended)

`ollama run qwen2.5:latest --keepalive=-1`

Then run the `lightrag_ollama_demo.py  `as usual.

According to my exps this slowness was mainly attributed to this issue where the api cant make any post/get requests.

Alternatively you can also edit the ollama.service file (but i recommend the earlier approach with cli: 
https://www.reddit.com/r/ollama/comments/1cnxnrv/how_to_set_keepalive_1_on_ollama_linux/

**Comment by Jaykumaran** [comment]
```
import os
import logging
from lightrag import LightRAG, QueryParam
from lightrag.llm import ollama_model_complete, ollama_embedding
from lightrag.utils import EmbeddingFunc

WORKING_DIR = "./dickens"

logging.basicConfig(format="%(levelname)s:%(message)s", level=logging.INFO)

if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)

rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=ollama_model_complete,
    llm_model_name="gemma2:2b",  #qwen2.5
    llm_model_max_async=4,
    llm_model_max_token_size=32000,
    llm_model_kwargs={"host": "http://localhost:11434", "options": {"num_ctx": 32768}},
    embedding_func=EmbeddingFunc(
        embedding_dim=768,
        max_token_size=8192,
        func=lambda texts: ollama_embedding(
            texts, embed_model="nomic-embed-text", host="http://localhost:11434"
        ),
    ),
)

#Adjust the relative path accordingly
with open("../book.txt", "r", encoding="utf-8") as f:
    rag.insert(f.read())

# Perform naive search
print(
    rag.query("What are the top themes in this story?", param=QueryParam(mode="naive"))
)

# Perform local search
print(
    rag.query("What are the top themes in this story?", param=QueryParam(mode="local"))
)

# Perform global search
print(
    rag.query("What are the top themes in this story?", param=QueryParam(mode="global"))
)

# Perform hybrid search
print(
    rag.query("What are the top themes in this story?", param=QueryParam(mode="hybrid"))
)
```

**Comment by Jaykumaran** [comment]
Additionally consider doing

` ollama serve`

to see logs of api requests. Which helps you to assess whether indexing is happening or the event got stuck.

```
[GIN] 2024/11/05 - 10:59:06 | 200 |   96.177812ms |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/11/05 - 10:59:06 | 200 |   96.018684ms |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/11/05 - 10:59:06 | 200 |   54.672653ms |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/11/05 - 10:59:06 | 200 |   95.050153ms |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/11/05 - 10:59:10 | 200 |  4.246976431s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2024/11/05 - 10:59:11 | 200 |  795.565994ms |       127.0.0.1 | POST     "/api/chat"
[GIN] 2024/11/05 - 10:59:11 | 200 |   96.205106ms |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/11/05 - 10:59:24 | 200 | 12.822827401s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2024/11/05 - 10:59:24 | 200 |   97.864892ms |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/11/05 - 10:59:24 | 200 |     3.73229ms |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/11/05 - 10:59:37 | 200 |   12.4699433s |       127.0.0.1 | POST     "/api/chat"
```

**Comment by ASAD-BE18** [comment]
Hi, thanks for your assistance.

**Comment by ASAD-BE18** [comment]
How can I format the response to JSON?
I know I can do this by using prompt but it will be very naive method and the output response may not be valid json

**Comment by Jaykumaran** [comment]
Can you be clear on how you would like your JSON response to be structured with some eg? 


Do you want the response like (I dont think so)

{
    "naive": {
        "query": "What is the capital of France?",
        "response": "The capital of France is Paris."
    },
    "hybrid": {
        "query": "What is the capital of France?",
        "response": "The capital of France is Paris, known for its art, fashion, and culture."
    }
}

**Comment by ASAD-BE18** [comment]
I know we have various modules like instructor, JSON parser for this task, but I am unable to figure it out where to plug these for the desired output

**Comment by Jaykumaran** [comment]
Hello,

The LightRAG class already has a basic convert_response_to_json as a param, may be you can refactor according to your need by creating a fork.  It implements as follows in .utils.py

![image](https://github.com/user-attachments/assets/b1513c54-8356-4f07-9c53-0eec27dc7823)

**Comment by Jaykumaran** [comment]
Based on recent experiments, llama3.1:8b works good.

**Comment by ASAD-BE18** [comment]
I am running the script in Kaggle, how could I set the timeout parameter there?

**Comment by Jaykumaran** [comment]
Hello,

With llama3.2:8b things are working good without need to explicitly set `--keepalive=-1m`. You can still do ollama serve to see what's happening BTS with api calls .

**Comment by adamwuyu** [comment]
> Hello,
> 
> Not sure about llama models.
> 
> gemma2:2b and qwen2.5:7b works fine in my case when tried locally on RTX3080Ti. However it takes like around 15-20 minutes for Charles Dickens sample book given in the demo.

Hi，did you try qwen2.5:14b, does is much better than qwen2.5:7b?

**Comment by Jaykumaran** [comment]
Hello,

I tried with qwen models, however i felt llama3.1 8b worked for my simple example worked.

My Blog: https://learnopencv.com/lightrag/

**Comment by adamwuyu** [comment]
> Hello,
> 
> I tried with qwen models, however i felt llama3.1 8b worked for my simple example worked.
> 
> My Blog: https://learnopencv.com/lightrag/

Nice article!
