### ISSUE TITLE
How to use Gemini with OpenAI Compatible 

### ISSUE THREAD

**Issue by Jaykumaran** [HKUDS/LightRAG#175]
Hi Team,

Can i get reference for using Gemini models with OpenAI proxy server for running my experiments with LightRAG.

Also any plans to include Gemini model example scripts anyitme soon?

 Looking Forward to hear from you.

**Comment by LarFii** [comment]
We are not very familiar with the Gemini model. But `examples` directory offers various model methods that might assist you.

**Comment by Jaykumaran** [comment]
Hey Team,

Thanks for the response. It would be really helpful if you could explore that aspect as well. Gemini offers 1,500 free API calls per day, so it would be great to experiment with robust models like Gemini to assess performance rather than just using 2B Ollama models.


Ref: [Gemini API Pricing](https://ai.google.dev/pricing#1_5flash)

**Comment by vanhdz2611** [comment]
@Jaykumaran Hi, are you successfully using the Gemini API ?

**Comment by Jaykumaran** [comment]
Hello,

Recently Gemini natively integrated OpenAI Proxy and here is the ref:

https://developers.googleblog.com/en/gemini-is-now-accessible-from-the-openai-library/

**Comment by evandromassa** [comment]
"Even with Gemini configured through the OpenAI bind, I'm getting an 'Invalid API KEY' error. My key isn't from Google Cloud's VertexAI, but from AISTUDIO (where Gemini models are free).

Any plans for direct Gemini API support?"

**Comment by Jaykumaran** [comment]
Hey,

It should work with ai studio.



```
https://ai.google.dev/gemini-api/docs/openai
```

Also setting up a free google cloud account is also useful.





```
# Step1: GCloud CLI locally : https://cloud.google.com/sdk/docs/install#deb
# Step2: Enable vertex ai api, for same account
# Step3: Test first whether your api works with:https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/call-vertex-using-openai-library#client-setup

import os
import asyncio
import numpy as np
from lightrag import LightRAG, QueryParam
from lightrag.llm import openai_complete_if_cache, openai_embedding, ollama_embedding
from lightrag.utils import EmbeddingFunc
import vertexai
import google.auth
from google.auth import default, transport

# Set project ID and location for Vertex AI
PROJECT_ID = "gen-lang-client-0302685567"
location = "us-central1"

# Initialize Vertex AI
vertexai.init(project=PROJECT_ID, location=location)

# Programmatically get an access token
credentials, _ = default(scopes=["https://www.googleapis.com/auth/cloud-platform"])
auth_request = transport.requests.Request()
credentials.refresh(auth_request)

# Set working directory
WORKING_DIR = "./gemini_dickens"
if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)


# Function to call the LLM model
async def llm_model_func(prompt, system_prompt=None, history_messages=[], **kwargs) -> str:
    return await openai_complete_if_cache(
        "google/gemini-1.5-flash",
        prompt,
        system_prompt=system_prompt,
        history_messages=history_messages,
        api_key=credentials.token,
        base_url=f"https://{location}-aiplatform.googleapis.com/v1beta1/projects/{PROJECT_ID}/locations/{location}/endpoints/openapi",
        **kwargs,
    )


# Function to get embeddings
async def embedding_func(texts: list[str]) -> np.ndarray:
    return await openai_embedding(
        texts,
        model="google/gemini-1.5-flash-002",
        api_key=credentials.token,
        base_url=f"https://{location}-aiplatform.googleapis.com/v1/projects/{PROJECT_ID}/locations/{location}/endpoints/openapi/embeddings/create",
    )


#Function to get the embedding dimension
async def get_embedding_dim():
    test_text = ["This is a test sentence."]
    embedding = await embedding_func(test_text)
    return embedding.shape[1]


# Main function to run queries
async def main():
    try:
        # embedding_dimension = await get_embedding_dim()
        # print(f"Detected embedding dimension: {embedding_dimension}")

        rag = LightRAG(
            working_dir=WORKING_DIR,
            llm_model_func=llm_model_func,
            llm_model_max_async=1,  # Free tier offers limited no. of concurrent api calls per min
            embedding_func=EmbeddingFunc(
                embedding_dim=1024,
                max_token_size=8192,
                func=lambda texts: ollama_embedding(texts, embed_model="mxbai-embed-large", host="http://localhost:11434"),
            ),
        )

        # Insert text into the RAG
        with open("../book.txt", "r", encoding="utf-8") as f:
            await rag.ainsert(f.read())

        # Perform various queries
        print(await rag.aquery("What are the top themes in this story?", param=QueryParam(mode="naive")))
        print(await rag.aquery("What are the top themes in this story?", param=QueryParam(mode="local")))
        print(await rag.aquery("What are the top themes in this story?", param=QueryParam(mode="global")))
        print(await rag.aquery("What are the top themes in this story?", param=QueryParam(mode="hybrid")))

    except Exception as e:
        print(f"An error occurred: {e}")


if __name__ == "__main__":
    asyncio.run(main())
```

`https://github.com/Jaykumaran/Retrieval-Augmented-Generation/blob/main/gemini-openai-proxy.py`

https://github.com/spmallick/learnopencv/tree/master/LightRAG-Legal

**Comment by evandromassa** [comment]
Thanks @Jaykumaran, but I’m using the LightRAG API and configuring it directly in the .env.
The API KEY error occurs whenever I update the settings in .env:

```
LLM_MODEL=gemini-2.5-flash
LLM_BINDING_API_KEY="XXX"
LLM_BINDING_HOST="https://generativelanguage.googleapis.com/v1beta/openai/"
```

**Comment by marcinszymanski** [comment]
Hi, @evandromassa remove " from API key and host, and it will work.

**Comment by evandromassa** [comment]
> Hi, [@evandromassa](https://github.com/evandromassa) remove " from API key and host, and it will work.

I've removed the " from LLM_BINDING_API_KEY and LLM_BINDING_HOST, but i got same error:

2025-09-18 19:26:36,235 - lightrag - INFO - [lightrag] Total nodes: 310, Selected nodes: 310
2025-09-18 19:26:36,375 - lightrag - INFO - [lightrag] Subgraph query successful | Node count: 310 | Edge count: 367
2025-09-18 19:26:39,679 - lightrag - INFO - limit_async: 4 new workers initialized
2025-09-18 19:26:40,788 - lightrag - WARNING - high_level_keywords is empty
2025-09-18 19:26:40,788 - lightrag - WARNING - Forced low_level_keywords to origin query: teste
2025-09-18 19:26:40,789 - lightrag - INFO - Process 551 building query context...
2025-09-18 19:26:40,901 - lightrag - WARNING - Failed to pre-compute query embedding: Error code: 400 - {'error': {'code': 400, 'message': 'API key not valid. Please pass a valid API key.', 'status': 'INVALID_ARGUMENT', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'API_KEY_INVALID', 'domain': 'googleapis.com', 'metadata': {'service': 'generativelanguage.googleapis.com'}}, {'@type': 'type.googleapis.com/google.rpc.LocalizedMessage', 'locale': 'en-US', 'message': 'API key not valid. Please pass a valid API key.'}]}}
2025-09-18 19:26:40,901 - lightrag - INFO - Query nodes: teste, top_k: 40, cosine: 0.2
2025-09-18 19:26:40,904 - lightrag - INFO - limit_async: 8 new workers initialized
2025-09-18 19:26:41,130 - lightrag - ERROR - limit_async: Error in decorated function: Error code: 400 - {'error': {'code': 400, 'message': 'API key not valid. Please pass a valid API key.', 'status': 'INVALID_ARGUMENT', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'API_KEY_INVALID', 'domain': 'googleapis.com', 'metadata': {'service': 'generativelanguage.googleapis.com'}}, {'@type': 'type.googleapis.com/google.rpc.LocalizedMessage', 'locale': 'en-US', 'message': 'API key not valid. Please pass a valid API key.'}]}}
2025-09-18 19:26:41,154 - uvicorn.access - INFO - 10.14.2.132:58570 - "POST /query/stream HTTP/1.1" 500

I tried the request with same API_KEY in Insomnia and works fine...

curl "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer GEMINI_API_KEY" \
-d '{
    "model": "gemini-2.5-flash",
    "reasoning_effort": "low",
    "messages": [
        {"role": "user", "content": "Explain to me how AI works"}
      ]
    }

**Comment by evandromassa** [comment]
I finally managed to configure GEMINI. For anyone who encounters difficulties (like I did), below is the correct configuration (using GEMINI for the LLM and OPENAI for the EMBEDDINGS):

```
LLM_BINDING=openai
LLM_MODEL=gemini-2.0-flash-exp
LLM_BINDING_API_KEY=XXXXX
LLM_BINDING_HOST=https://generativelanguage.googleapis.com/v1beta/openai

EMBEDDING_BINDING=openai
EMBEDDING_MODEL=text-embedding-3-small
EMBEDDING_BINDING_API_KEY="XXXX"
EMBEDDING_DIM=1536
EMBEDDING_BINDING_HOST=https://api.openai.com/v1

```

Thanks to everyone!!!
