### ISSUE TITLE
Step_3 error, too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by yiwalk23li** [HKUDS/LightRAG#176]
在运行完step_3之后，得到的结果只有error
![image](https://github.com/user-attachments/assets/a986be32-ab7e-4822-aa51-c584645e54f8)
在运行的过程中并没有报错。
![image](https://github.com/user-attachments/assets/a4975829-4c5b-4763-bcab-3b5aef9084d7)
使用的模型和参数都是默认值。这是哪方面的问题呢？

**Comment by LarFii** [comment]
这个bug昨天修复好了，clone最新的代码即可
