### ISSUE TITLE
Not able to run code based on examples/lightrag_ollama_demo.py

### ISSUE THREAD

**Issue by 32bitmicro** [HKUDS/LightRAG#179]
When I run  code based  on examples/lightrag_ollama_demo.py I get following error, see below.
This happens with` llm_model_name="gemma2:2b"`

```
python3.11/site-packages/tiktoken/model.py", line 84, in encoding_name_for_model
    raise KeyError(
KeyError: 'Could not automatically map gpt-4o-mini to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'
```

Can you suggest a solution?

**Comment by Jaykumaran** [comment]
Hello,

I didnt face error with `lightrag_ollama_demo.py`, when i used the sample code from repo using gemma2:2b.

I created a new env, followed setup procedure as listed under readme.

Then `ollama pull gemma2:2b`

**Comment by 32bitmicro** [comment]
Well the error is about wrong tokeniser in my python 3.11 environment maybe that is the problem.
What python version do you use?  
My script references local docs, I will try with what you have posted and let you know.
I actually got it running by adding this line:
`tiktoken_model_name="gpt2" `
just before
` embedding_func=EmbeddingFunc(`
But it did not seem to make any progress and I had to kill it after couple of hours.
How long was it running on your PC?

**Comment by 32bitmicro** [comment]
Here is the result, still seeing the error
INFO:lightrag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
  File ./rag_ollama_demo.py", line 31, in <module>
    rag.insert(f.read())
  File "miniconda3/lib/python3.11/site-packages/lightrag/lightrag.py", line 167, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/site-packages/lightrag/lightrag.py", line 192, in ainsert
    for dp in chunking_by_token_size(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/site-packages/lightrag/operate.py", line 32, in chunking_by_token_size
    tokens = encode_string_by_tiktoken(content, model_name=tiktoken_model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/site-packages/lightrag/utils.py", line 121, in encode_string_by_tiktoken
    ENCODER = tiktoken.encoding_for_model(model_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/site-packages/tiktoken/model.py", line 97, in encoding_for_model
    return get_encoding(encoding_name_for_model(model_name))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/lib/python3.11/site-packages/tiktoken/model.py", line 84, in encoding_name_for_model
    raise KeyError(
KeyError: 'Could not automatically map gpt-4o-mini to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'

**Comment by Jaykumaran** [comment]
I'm using 3.10. I've not changed anything from the og script.
