### ISSUE TITLE
Allow for Local Model

### ISSUE THREAD

**Issue by jasonbaptist-sh** [HKUDS/LightRAG#18]
Given the decrease in API calls compared to Graphrag - would it be possible (sensible) to modify this such that it also can work with local offline models through ollama or similar?

**Comment by LarFii** [comment]
Thanks for your attention! It currently supports Huggingface models, including local models, and we plan to add Ollama support in future updates as well.  For a usage demo with Huggingface, please refer to [Using Hugging Face Models](https://github.com/HKUDS/LightRAG/tree/main#using-hugging-face-models).
