### ISSUE TITLE
图谱构建的过程中没有做指代消解和消歧

### ISSUE THREAD

**Issue by gcy0926** [HKUDS/LightRAG#184]
RT，缺少上述过程的话，图谱中会包含大量的重复实体，这样检索和生成都会受到影响

**Comment by gcy0926** [comment]
_merge_nodes_then_upsert这个函数里面只根据名称获取已有节点，可以通过查语义相似，结合大模型做消歧、去重的过程。

**Comment by LarFii** [comment]
感谢您的建议！后续我们会考虑加入这一步。
