### ISSUE TITLE
Is there any idea for delete some inserted document from the graph

### ISSUE THREAD

**Issue by Maxch3306** [HKUDS/LightRAG#190]
Is there any idea for delete some inserted document from the graph?

**Comment by kkk935208447** [comment]
It feels like the increase in the lightrag documentation library is irreversible.

**Comment by Maxch3306** [comment]
What if we add the filename or GUID to the cells for each document?

**Comment by LarFii** [comment]
We are exploring suitable deletion methods and currently plan to delete from the perspectives of entities and relationships.
