### ISSUE TITLE
Please add an openai api compatible call method.

### ISSUE THREAD

**Issue by xldistance** [HKUDS/LightRAG#193]
I called the lightrag api in continue and realized that the lightrag api doesn't implement the openai api call method
![QQ20241102-104048](https://github.com/user-attachments/assets/b181bdd8-8431-45ad-b6d0-27a514d62d13)

**Comment by Jaykumaran** [comment]
Are you looking for this 

[lightrag_api_openai_compatible_demo.py](https://github.com/HKUDS/LightRAG/blob/main/examples/lightrag_api_openai_compatible_demo.py)
