### ISSUE TITLE
How to set llm parameter

### ISSUE THREAD

**Issue by albertimff** [HKUDS/LightRAG#194]
I adjust the parameter in the lightrag.py 
![image](https://github.com/user-attachments/assets/e7f8d48f-1bb9-4e51-9132-b652aa90bbe6)
but when i run lightrag_openai_compatible_demo.py
the terminal and log shows that i didn't change parameter
![image](https://github.com/user-attachments/assets/a6801af2-d569-49c1-92ba-d1b9b22763e3)
![image](https://github.com/user-attachments/assets/319495e3-a98b-488f-92d5-51f8afa3e5da)

WHY

**Comment by xldistance** [comment]
Do not use llm_model_func
```
# Initialize the LightRAG instance
rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=ollama_model_complete,
    llm_model_name="qwen2:32b",
    llm_model_max_token_size=11000,
    llm_model_kwargs={"host": "http://localhost:11434", "options": {"num_ctx": 11000}},
    embedding_func=EmbeddingFunc(
        embedding_dim=1024,
        max_token_size=8192,
        func=lambda texts: openai_embedding(
            texts, model="bge-m3", base_url="http://127.0.0.1:9997/v1", api_key="xinference"
        ),
    ),
)
```

**Comment by albertimff** [comment]
how to adjust queryparam's parameters.Thanks!

**Comment by xldistance** [comment]
> how to adjust queryparam's parameters.Thanks!

The code above already writes the parameters

**Comment by albertimff** [comment]
![image](https://github.com/user-attachments/assets/5c2b1efc-de3c-4dca-b4de-9f991e49afb7)
I intend for this
