### ISSUE TITLE
Working with huggingface models, encountered 'Didn't extract any relationships, maybe your LLM is not working.'

### ISSUE THREAD

**Issue by iamwodsink22** [HKUDS/LightRAG#195]
rag=LightRAG(working_dir='./model',
             llm_model_func=hf_model_complete,
             llm_model_name='meta-llama/Llama-3.2-1B-Instruct',
             embedding_func=EmbeddingFunc(embedding_dim=384,
             func=lambda texts:hf_embedding(texts,
             tokenizer=AutoTokenizer.from_pretrained("sentence-transformers/all-MiniLM-L6-v2"),
             embed_model=AutoModel.from_pretrained("sentence-transformers/all-MiniLM-L6-v2"))))

When I query the rag in naive mode. I encounter index error 'content'. In local and global mode it gives 'Sorry, I am unable to provide answer'. For hybrid mode it gives some random unrelated answer. This probably means the llm is not working really ?.

I have seen the same issue for ollama model where the apparent solution was to increase the context window(ctx_parameter). Is there any parameters I can tweak for huggingface models ?

**Comment by RainDayDream** [comment]
I use Qwen 2.5:7b for LightRAG, but the relations extracted are only 2. I'm really confused about this result.

**Comment by RainDayDream** [comment]
I try to run it again,and get a good result. I think the reason is that there were  other processes using VRAM when i ran LightRAG the first time.

![mmexport1730738118878.png](https://github.com/user-attachments/assets/86093e78-e653-4a2d-9e6c-129db4879829)
