### ISSUE TITLE
content_keywords有什么用？

### ISSUE THREAD

**Issue by gujiachun** [HKUDS/LightRAG#199]
通过源码发现，大模型会返回 content_keywords这个属性。但源码中对content_keywords没有存储起来
在检索的时候，也没有用到content_keywords
content_keywords起到什么作用？

===============================================================================

Through the source code, it was found that the large model will return the content_keywords attribute. But the content_keywords are not stored in the source code
When searching, content_keywords were not used either
What is the function of content_keywords?

**Comment by LarFii** [comment]
The `content_keywords` is a reserved interface, and we haven't developed any functionality based on it yet.
