### ISSUE TITLE
Reproducing the results from RQ1 and RQ2

### ISSUE THREAD

**Issue by NumberChiffre** [HKUDS/LightRAG#2]
Hey LightRAG team,

I just read your paper on arXiv and it looks really interesting! I noticed you've got some great benchmark results that outperform other similar projects (**[nano-graphrag](https://github.com/gusye1234/nano-graphrag/)** :D)

I was wondering if you could share the code you used to reproduce these benchmark experiments? It would be super helpful for those of us trying to understand and implement your findings. 

Adding some details on how to run the benchmarks would be awesome too. It's always exciting to see advancements in this field, and being able to replicate the results helps everyone learn and improve. 

Thanks in advance for considering this! Looking forward to diving deeper into your work.

Cheers!

**Comment by LarFii** [comment]
Thanks for your attention! We have updated our reproduction [steps](https://github.com/HKUDS/LightRAG/tree/main?tab=readme-ov-file#reproduce), and all the code can be found in the `./reproduce`.
