### ISSUE TITLE
429 Too Many Requests for GPT 4o mini 

### ISSUE THREAD

**Issue by solaius** [HKUDS/LightRAG#20]
When running the demo code with book.txt, everything moves smoothly for 50-100 openai requests.  It is moving so fast that I start getting the 429 too many requests.  

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"

Is it possible to load the whole book in one go?  If not how is that controlled?  I don't see how the demo can be completed when ingesting the whole book.  It seems like the rate limit will be hit on the tokens per minute unless this can be slowed down heavily.  

Terminal output attached.
[Error.txt.txt](https://github.com/user-attachments/files/17388187/Error.txt.txt)

**Comment by solaius** [comment]
Thanks for the quick answer! I will be rerunning it in a little bit

**Comment by LarFii** [comment]
You're welcome! Hope it goes smoothly—feel free to reach out if needed!

**Comment by solaius** [comment]
It took about 6 minutes (5 restarts) to get through it all, but it worked! Cheers.

**Comment by LarFii** [comment]
Thanks for your patience!
