### ISSUE TITLE
extract package reference

### ISSUE THREAD

**Issue by solomem** [HKUDS/LightRAG#201]
Can you please provide a package reference used in the extract code?
Thanks

Sorry I meant the Amazon Textract example given:

```python
import textract

file_path = 'TEXT.pdf'
text_content = textract.process(file_path)

rag.insert(text_content.decode('utf-8'))
```

The module `textract`, have you included it anywhere in the code? Many thanks

**Comment by LarFii** [comment]
I’m not quite sure I understand what you need. Could you describe it in more detail?

**Comment by keshiriotinto** [comment]
Sorry I meant the Amazon Textract example given:

```python
import textract

file_path = 'TEXT.pdf'
text_content = textract.process(file_path)

rag.insert(text_content.decode('utf-8'))
```

The module `textract`, have you included it anywhere in the code? Many thanks

**Comment by WangAo-0** [comment]
> 我不太确定我是否理解了您的需求。您能更详细地描述一下吗？

textract这个包如何安装，似乎有冲突
![image](https://github.com/user-attachments/assets/8aaa6c1c-7c95-4b21-a61e-c62ec9f6f703)

**Comment by solomem** [comment]
> > 我不太确定我是否理解了您的需求。您能更详细地描述一下吗？
> 
> textract这个包如何安装，似乎有冲突 ![image](https://private-user-images.githubusercontent.com/69076657/384264434-8aaa6c1c-7c95-4b21-a61e-c62ec9f6f703.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjU2MDUsIm5iZiI6MTczMTA2NTMwNSwicGF0aCI6Ii82OTA3NjY1Ny8zODQyNjQ0MzQtOGFhYTZjMWMtN2M5NS00YjIxLWE2MWUtYzYyZWM5ZjZmNzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDExMjgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMDhhZTYzZjc2MDRjNGNkODhjZTZiMDJjNTU3MjE5MjExOTJlZDQ4MTM4ZDA0ZDgyNmUzMjk0MmFmZjRmYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kpJqnfKcEs7iNglDLnwp4qBqAEBGWXlKJYhXAK_EJ2E)

I was thinking the same, https://pypi.org/project/textract/#history is definitely not the package used.

**Comment by minglai1994** [comment]
I tried pip install textract==1.5.0, it works fine for me.
