### ISSUE TITLE
Some questions about graph output comparison with GraphRAG

### ISSUE THREAD

**Issue by WinstonCHEN1** [HKUDS/LightRAG#202]
While reproducing, I noticed that the graph in the output file was slightly different from GraphRAG.

Are the steps for building a graph in LightRAG the same as those for building a graph in GraphRAG? For example, are the same interfaces or logic used?

If so, how should I use the outputs generated by the two projects with each other? Is it possible?

 If not, what is the difference?
 
 Could you please give me more details? Thanks a lot.

**Comment by LarFii** [comment]
The main difference between LightRAG and GraphRAG in the extraction process is that LightRAG omits communities and instead introduces keywords, making them incompatible with each other. For more details, please refer to our paper.

**Comment by WinstonCHEN1** [comment]
Thanks a lot!!!
