### ISSUE TITLE
enabling history for a series of questions and answers

### ISSUE THREAD

**Issue by amirsa66** [HKUDS/LightRAG#205]
hi there

If I want to use LightRAG to build a bot for questioning and answering, how can i enable history that best fit with this repo?

**Comment by amirsa66** [comment]
@LarFii should I make use of `history_messages` in the llm.py?

**Comment by ziudeso** [comment]
@amirsa66 did you manage to understand how to integrate the history?

**Comment by amirsa66** [comment]
> @amirsa66 did you manage to understand how to integrate the history?

Yes, it's OK

**Comment by ziudeso** [comment]
@amirsa66 I'm actually asking how did you do that? =D

**Comment by amirsa66** [comment]
> @amirsa66 I'm actually asking how did you do that? =D

I did it on Streamlit:
`import os
import streamlit as st
from lightrag import LightRAG, QueryParam
from lightrag.llm import gpt_4o_mini_complete
from dotenv import load_dotenv

# Load the .env file
load_dotenv()
# Access the API key
api_key = os.getenv("OPENAI_API_KEY")

WORKING_DIR = "./inputText"

if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)

# Initialize LightRAG instance
rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=gpt_4o_mini_complete
)

#### Open the file with UTF-8 encoding
# with open("./771-807.txt", "r", encoding="utf-8") as f:
#     content = f.read()
#     rag.insert(content)


# Streamlit UI setup
st.set_page_config(page_title="AI bot", page_icon="🖥️")
st.title("AI bot")

st.markdown(unsafe_allow_html=True)

# Initialize chat history in session state
if "chat_history" not in st.session_state:
    st.session_state.chat_history = [
        {"role": "AI", "content": "hi, how can I help?"},
    ]

# Function to construct the conversation prompt
def construct_prompt(user_input, chat_history):
    conversation = ""
    for message in chat_history:
        if message["role"] == "Human":
            conversation += f"user: {message['content']}\n"
        elif message["role"] == "AI":
            conversation += f"AI bot: {message['content']}\n"
    # Add the current user input
    conversation += f"user: {user_input}\nAI bot: "
    return conversation

# Function to query LightRAG and get the response
def get_response(prompt):
    response = rag.query(
        prompt,
        param=QueryParam(mode="hybrid")
    )
    return response

# Chat input widget for user to ask questions
user_query = st.chat_input("ask me ...")
if user_query:
    # Construct the conversation prompt including history
    prompt = construct_prompt(user_query, st.session_state.chat_history)

    # Get AI response
    response = get_response(prompt)

    # Add user question and AI response to chat history
    st.session_state.chat_history.append({"role": "Human", "content": user_query})
    st.session_state.chat_history.append({"role": "AI", "content": response})

# Display chat history
for message in st.session_state.chat_history:
    if message["role"] == "AI":
        with st.chat_message("AI"):
            st.write(message["content"])
    elif message["role"] == "Human":
        with st.chat_message("Human"):
            st.write(message["content"])
`

**Comment by ziudeso** [comment]
Hu @amirsa66 is that the whole code?
I'm getting `TypeError: MarkdownMixin.markdown() missing 1 required positional argument: 'body'` when running it as streamlit run test_history.py

**Comment by ziudeso** [comment]
Ok nevermind works like a charm, great job @amirsa66 !!
