### ISSUE TITLE
Error in naive queries with None

### ISSUE THREAD

**Issue by FlankerV2** [HKUDS/LightRAG#206]
Hello!
I'm experiencing errors with some LightRAG.query calls with a naive query type that result in None.

In the naive query, the error occurs at this line:
https://github.com/HKUDS/LightRAG/blob/main/lightrag/operate.py#L1052
```
    maybe_trun_chunks = truncate_list_by_token_size(
        chunks,
        key=lambda x: x["content"], --ERROR
        max_token_size=query_param.max_token_for_text_unit,
    )
```

A small debug showed that chunks contains objects of type None, which causes the error.

Perhaps it would be a good idea to add checks at previous steps when retrieving this parameter to not return None types

**Comment by LarFii** [comment]
Thanks @benx13, it has been fixed. [pr#215](https://github.com/HKUDS/LightRAG/pull/215#issue-2636899023)
