### ISSUE TITLE
访问api路由错误

### ISSUE THREAD

**Issue by LHB-kk** [HKUDS/LightRAG#207]
运行 python examples/lightrag_api_openai_compatible_demo.py , 之后访问query路由：
curl -X POST "http://127.0.0.1:8020/query" -H "Content-Type: application/json" -d '{"query": "my query", "mode": "hybrid"}'
报错：{"detail":"There is no current event loop in thread 'ThreadPoolExecutor-0_0'."}

**Comment by Dormiveglia-elf** [comment]
Make sure you pull the latest code. It seems that you are trying to execute asynchronous code in a thread that doesn't have an event loop set up.

**Comment by LHB-kk** [comment]
> Make sure you pull the latest code. It seems that you are trying to execute asynchronous code in a thread that doesn't have an event loop set up.

Thank you! But I had pull the latest code. And I try it again, but it not work for me. 
The terminal log:
![image](https://github.com/user-attachments/assets/a9c9d4e9-ab18-4e97-8634-76cb9f19d3e2)

![image](https://github.com/user-attachments/assets/6fb92f0b-afc1-4da5-8ecd-1de1ea34f400)

**Comment by kelvennn** [comment]
> 运行 python Examples/lightrag_api_openai_completed_demo.py ，之后访问query路由： curl -X POST " http://127.0.0.1:8020/query " -H "Content-Type: application/json" -d '{"query": "我的查询", "mode": "hybrid"}' 报错：{"detail":"线程 'ThreadPoolExecutor-0_0' 中没有当前事件循环。"}

嗨，我遇到同样的问题，你是怎么解决的呢？
