### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by ASAD-BE18** [HKUDS/LightRAG#210]
How can I structure the query output response to JSON?

**Comment by Jaykumaran** [comment]
Hello,

The LightRAG class already has a basic convert_response_to_json as a param, may be you can refactor according to your need by creating a fork.  It implements as follows in .utils.py

![image](https://github.com/user-attachments/assets/b1513c54-8356-4f07-9c53-0eec27dc7823)

Hope it helps.
