### ISSUE TITLE
Regarding the reproduction of comparative experimental models.

### ISSUE THREAD

**Issue by Idol-Dou2021** [HKUDS/LightRAG#218]
Dear developer, hello. I would like to reproduce the relevant comparison models that appeared in the experiment. How can I ensure that their conditions are the same? I have carefully reviewed the code in the repository and did not find any relevant comparison model code. What should I do and where can I find this code?

**Comment by LarFii** [comment]
Each baseline has its own GitHub repository; we directly cloned the source code from those repositories.
