### ISSUE TITLE
Logs aren't easy to understand 

### ISSUE THREAD

**Issue by Jaykumaran** [HKUDS/LightRAG#223]
Hello, 

**Current logging isn't much easy to understand. It would be nice if there are multiple intermediate logs at each stage as described in the readme workflow image.** As of now everything is more abstract, so much though process has to go behind what went wrong when stale occurs. 

I'm discussing mainly my experience with ollama integration is much unpleasant. Spending past 1 week to properly index my own doc of 250 pages. Resources aren't much constrained from my end. The api call to chat gets freezed.

Also consider added different color other than white when an main log or stage have completed. For eg: ` INFO:lightrag:[Entity Extraction]... could have been in different color `

```
INFO:httpx:HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
INFO:lightrag:[Entity Extraction]...
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
```

**Comment by Jaykumaran** [comment]
![image](https://github.com/user-attachments/assets/c71e653d-5152-4798-952f-196577efa7b3)

**Comment by LarFii** [comment]
Thanks for your support for LightRAG. We apologize for the unpleasant with Ollama. Moving forward, we’ll revise the log recording format to improve clarity.
