### ISSUE TITLE
可以增加调用本地ollama的方法

### ISSUE THREAD

**Issue by hznnnnnn** [HKUDS/LightRAG#23]
可以增加以下调用本地ollama的办法，把openai_async_client换成ollama_client，只有openai的话对穷哥们儿有点不友好。然后就是用tiktoken的话只能使用openai的模型，可以加个判断如果是调用的本地的模型的话走另一条线，比如说transformers的AutoTokenizer。运行的时候bug也有不少。

**Comment by LarFii** [comment]
Ollama正在调试中今天可以发布，Huggingface的支持已经添加好了[Using Hugging Face Models](https://github.com/HKUDS/LightRAG/tree/main?tab=readme-ov-file#using-hugging-face-models)
