### ISSUE TITLE
Workflow image in readme  is 404 not found.

### ISSUE THREAD

**Issue by Jaykumaran** [HKUDS/LightRAG#231]
Hey Team,

The workflow image in readme is no longer accessible. Kindly look into this.

It was a nice reference to look out everytime about the flow. 

![image](https://github.com/user-attachments/assets/69ba8a6a-ddf7-42d5-9648-9b8005b956f7)

**Comment by Jaykumaran** [comment]
Now its working. I think its better to have it inplace under media or assets folder instead of directed by a link.

Anyways thanks

**Comment by LarFii** [comment]
Thank you for your suggestion. Are you referring to the Overall Architecture or the Algorithm Flowchart? I will make the necessary changes right away.

**Comment by Jaykumaran** [comment]
Hello,

Thanks, Yes I'm referring to that.

By referring that we at LearnOpenCV recreated the flowchart - LightRAG Indexing and Querying separately.


1. https://learnopencv.com/wp-content/uploads/2024/11/LightRAG-VectorDB-Json-KV-Store-Indexing-Flowchart-scaled.jpg
2. https://learnopencv.com/wp-content/uploads/2024/11/LightRAG-Querying-Flowchart-Dual-Level-Retrieval-Generation-Knowledge-Graphs-scaled.jpg


I can share full resolution of this image if required.

**Comment by Jaykumaran** [comment]
@LarFii, I’ve written an article on LearnOpenCV about using LightRAG for legal document analysis. Let me know if you could give it a read and provide suggestions for improvement. I'm looking for any technical review and feedback.

Feel free to suggest any topics or explanations that I should include. While I've gone in-depth on legal analysis, I aimed to make it a starter reference for those working at the intersection of legal and LLM+RAG.

[Link to article](https://learnopencv.com/lightrag/)"

**Comment by LarFii** [comment]
We’ve read the article, and it’s very well written. There are many aspects we haven’t tested yet. Recently, we’ve been focused on conducting more dimension-based tests for LightRAG. After that, we’ll continue to improve its functionality. Please stay tuned for further updates.

**Comment by Jaykumaran** [comment]
@LarFii 

Hey Team,

Can you add my blog under this section in README.

![image](https://github.com/user-attachments/assets/5e5c31d7-8675-487c-bb4a-8521b42b7aa5)

**Comment by LarFii** [comment]
Yes, of course. I am doing it now.

**Comment by Jaykumaran** [comment]
Hey @LarFii 

Many thanks for adding the recreated flowchart of LearnOpenCV to the README. If possible, could you kindly add a backlink to the blog under the flowchart caption as a source. This will help to drive some new audience  to the blog.

Something like Figure 1: Flowchart - Img Caption : [Source](https://learnopencv.com/lightrag/).

Thanks 😃

**Comment by LarFii** [comment]
Of course, I'll update it shortly.
