### ISSUE TITLE
Failed to build hnswlib

### ISSUE THREAD

**Issue by aliasal** [HKUDS/LightRAG#24]
I am on Windows 10, running python 3.11 in venv 
pip install lightrag-hku
gives the error(s)
....
      ./python_bindings/bindings.cpp(910): warning C4996: 'pybind11_init': PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE
      ./python_bindings/bindings.cpp(911): warning C4996: 'pybind11::module_::module_': Use PYBIND11_MODULE or module_::create_extension_module instead
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
Failed to build hnswlib
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (hnswlib)

The path C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC.... exists and cl.exe is in it.
I added the path to the PATH-Variable in my environments variables
I installed VS Code (full), restarted...

I have no idea what to do now?

**Comment by LarFii** [comment]
All our current testing has been done on Linux. We will now conduct tests on Windows and work on resolving the issue as soon as possible. Thank you for your patience!

**Comment by MrGidea** [comment]
> 我在 Windows 10 上，在 venv pip install lightrag-hku 中运行 python 3.11 出现错误 .... ./python_bindings/bindings.cpp（910）：警告 C4996：“pybind11_init”：PYBIND11_PLUGIN已弃用，请使用 PYBIND11_MODULE./python_bindings/bindings.cpp（911）：警告 C4996：“pybind11：：module_：：module_”：请改用 PYBIND11_MODULE 或 module_：：create_extension_module 错误：命令“C：\Program Files （x86）\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe”失败，退出代码 2 [输出结束]
> 
> 注意：此错误源自子进程，可能不是 pip 的问题。错误：为 hnswlib 构建轮子失败 无法构建 hnswlib 错误：错误：无法为某些基于 pyproject.toml 的项目 （hnswlib） 构建可安装轮子
> 
> 路径 C：\Program Files （x86）\Microsoft Visual Studio\2022\BuildTools\VC...。存在，并且 cl.exe 在其中。我在安装了 VS Code（完整）的环境变量中添加了 PATH-Variable 的路径，重新启动了......
> 
> 我现在不知道该怎么办？
下载Visual Studio2022，在勾选相关库的时候直接点击【使用C++的桌面开发】安装上相关的C++依赖，安装完成后重新执行命令就好了，网址：https://blog.csdn.net/qq_40600379/article/details/131408154

**Comment by MrGidea** [comment]
If you have sufficient memory, install Visual Studio 2022 and directly select "Desktop development with C++" to install the relevant C++ dependencies. After the installation is complete, then execute pip install lightrag-hku.

**Comment by LarFii** [comment]
I found a solution in [stackoverflow](https://stackoverflow.com/questions/73969269/error-could-not-build-wheels-for-hnswlib-which-is-required-to-install-pyprojec), and I hope it helps!

**Comment by aliasal** [comment]
> If you have sufficient memory, install Visual Studio 2022 and directly select "Desktop development with C++" to install the relevant C++ dependencies. After the installation is complete, then execute pip install lightrag-hku.

I did that (downloaded about 10GB), but the error is still the same.

**Comment by aliasal** [comment]
> I found a solution in [stackoverflow](https://stackoverflow.com/questions/73969269/error-could-not-build-wheels-for-hnswlib-which-is-required-to-install-pyprojec), and I hope it helps!

I already tried several of the suggestions there. 
Something new was:

set HNSWLIB_NO_NATIVE=1
pip install HNSWLIB

But the error is still the same.

**Comment by LarFii** [comment]
I tried to ask GPT-4o, and got the response as follows:
```
It seems like the error is related to building hnswlib on Windows. You can try installing a precompiled version of hnswlib to bypass the need to build from source. To do this, run the following command:

pip install hnswlib --prefer-binary --no-build-isolation

This should allow you to install hnswlib without compiling it locally. I hope this helps!
```

**Comment by QinQG** [comment]
conda install conda-forge::hnswlib

**Comment by aliasal** [comment]
> pip install hnswlib --prefer-binary --no-build-isolation

This starts with a warning:
DEPRECATION: Loading egg at c:\users\arnd\desktop 3\verkin\vk\lib\site-packages\lightrag_hku-0.0.6-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting hnswlib
....
and ends in an error
...
     creating 'C:\Users\Arnd\AppData\Local\Temp\pip-modern-metadata-01l92h34\hnswlib.dist-info'
      error: invalid command 'bdist_wheel'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by aliasal** [comment]
> conda install conda-forge::hnswlib

One step forward. Thanks.
Now, when I run the test example with the dickens file I get:
OSError: [WinError 127] Die angegebene Prozedur wurde nicht gefunden. Error loading "C:\Users\Arnd\Desktop 3\Verkin\vk\Lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.

The path is valid and the file torch_python.dll is there.
I uninstalled and reinstalled torch, but no difference

**Comment by LarFii** [comment]
Can Torch be used normally in other cases? You might want to try running a Hugging Face model demo to see if Torch is working correctly.

**Comment by aliasal** [comment]
> Can Torch be used normally in other cases? You might want to try running a Hugging Face model demo to see if Torch is working correctly.

I created a new venv (python 3.11) and 
conda install conda-forge::hnswlib
pip install lightrag-hku

needed to install transformers afterwards

import os
is missing from the example script:
```
from lightrag import LightRAG, QueryParam
from lightrag.llm import gpt_4o_mini_complete, gpt_4o_complete
WORKING_DIR = "./dickens"
if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)
rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=gpt_4o_mini_complete  # Use gpt_4o_mini_complete LLM model
    # llm_model_func=gpt_4o_complete  # Optionally, use a stronger model
)
with open("./book.txt") as f:
    rag.insert(f.read())
...
```
Under Windows the directories don't work, I changed them to:
WORKING_DIR = "buch"  
note the missing "./" with the "." and/or "/" the kv_store and vdb json files are not stored (no error)

and had some problems with uft-8 encoding:

with open("buch/verkin.txt", encoding="utf-8") as f:
    rag.insert(f.read())


Now it is working:
![graph](https://github.com/user-attachments/assets/4200b919-d55b-40bd-86fa-3f548092ee65)

Thanks everyone

**Comment by manojkr19** [comment]
> conda install conda-forge::hnswlib

This helped fix the problem for me on Mac.  Thanks

**Comment by ahmadhatahet** [comment]
> conda install conda-forge::hnswlib

I was trying to install LightRAG in WSL from the git repo directly and this one solved my issue with "hnswlib".
