### ISSUE TITLE
How to integrate Different Vector databases & Graph Database instead of storing on local machine.

### ISSUE THREAD

**Issue by AdityaKalraShorthillsAI** [HKUDS/LightRAG#248]
How can I move away from local storage and integrate multiple vector and graph databases as options for storing embeddings and graph data. This will enhance scalability, improve performance, and provide flexibility in choosing database solutions based on specific requirements.

**Comment by LarFii** [comment]
You can refer to the implementation methods of [Neo4j](https://github.com/HKUDS/LightRAG/blob/main/lightrag/kg/neo4j_impl.py) and [Oracle Database](https://github.com/HKUDS/LightRAG/blob/main/lightrag/kg/oracle_impl.py).
