### ISSUE TITLE
Trouble importing ollama_embeding

### ISSUE THREAD

**Issue by Boadzie** [HKUDS/LightRAG#27]
`from lightrag.llm import ollama_embedding, ollama_model_complete
ImportError: cannot import name 'ollama_embedding' from 'lightrag.llm
`
- Python 3.11

**Comment by eaedk** [comment]
same here

**Comment by eaedk** [comment]
solved
when I installed from source

**Comment by Boadzie** [comment]
Let me try that.

**Comment by LarFii** [comment]
Since there seem to be some bugs in the Ollama part, it hasn't been uploaded to PyPI yet. For now, you'll need to install it from the source. I'll work on fixing it as soon as possible. Best regards!
