### ISSUE TITLE
Discord link again expired

### ISSUE THREAD

**Issue by JimTeva** [HKUDS/LightRAG#272]
Current discord link https://discord.gg/mvsfu2Tg is expired

**Comment by Z-oo883** [comment]
Still ineffective

**Comment by LarFii** [comment]
I have updated the link, but for some reason, setting the link to be permanently valid does not seem to work.

**Comment by JimTeva** [comment]
Looks like the problem is coming from the README file actually. Whatever browser I use, the link is still https://discord.gg/mvsfu2Tg.
<img width="847" alt="Screenshot 2024-11-13 at 22 09 26" src="https://github.com/user-attachments/assets/ab8931e7-f28a-48ed-b165-b76e5d2d734f">
But when I checked your commit, none of the previous link and the new link is https://discord.gg/mvsfu2Tg, see: 
<img width="559" alt="Screenshot 2024-11-13 at 22 09 10" src="https://github.com/user-attachments/assets/03cb7d56-4a73-4e23-8eb6-8d3cd041a5fb">
I just tried with a vpn and still the same, maybe a caching problem from github?

**Comment by LarFii** [comment]
I know why now, it's because I forgot to update the link in the news.

**Comment by JimTeva** [comment]
lol I didn't even see the discord button, sorry!
