### ISSUE TITLE
Some questions about the preprint manuscript

### ISSUE THREAD

**Issue by jeremyzhangsq** [HKUDS/LightRAG#28]
Hi @LarFii ,

Thank you for releasing this interesting work.
Maybe I have missed something, but I am confused about the experimental results in the preprint manuscript. 

For example, in Table 1, do the LightRAG in the same column have the same configuration? Why do these performances vary a lot? If they are not in the same configuration, could you explain this?

![WX20241016-234449](https://github.com/user-attachments/assets/5a9238f0-f0a3-4ec5-af03-a38a2c94485f)

Thanks.

Jeremy

**Comment by LarFii** [comment]
Hi @jeremyzhangsq,

Thank you for your question! Throughout the entire table, LightRAG uses the same configuration. The variation in values comes from our one-to-one evaluation method, where each baseline is compared individually with LightRAG. The percentage values represent the win rate, which explains the differences. For example, in the first row and first column, the value indicates that, in terms of comprehensiveness, LightRAG outperforms Naive RAG in 67.31% of the queries.

I hope this helps clarify the results!

Best regards,
Zirui

**Comment by dannis97500** [comment]
Hi @LarFii,

Thank you for releasing this interesting work. Perhaps we need the test scripts in the paper to help us accurately reproduce the experimental results. Can you provide them in future version updates?

Thanks.

Dannis
