### ISSUE TITLE
对于已有的三元组数据，可以怎么构建

### ISSUE THREAD

**Issue by laizef** [HKUDS/LightRAG#280]
看到的示例是从文本数据直接构建的，但我已经有了一些三元组数据，可以怎么构建？有没有对应的函数或者提示设置？

**Comment by laizef** [comment]
自问自答一下，通过改写prompt.py，可以提取csv文件中的实体和关系，最后的问答效果也还不错。同理，各类型的数据都可以用相似的方法解决。

**Comment by mcgillkwok** [comment]
能分享一下csv的来源数据在prompt.py是如何写的吗？
