### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Tian-ye1214** [HKUDS/LightRAG#290]
{args_hash: {"return": response.choices[0].message.content, "model": model}}
TypeError: 'NoneType' object is not subscriptable

使用调用OpenAI模型的代码，embedding模型为text-embedding-3-large，LLM为gpt-3.5-turbo。在vdb数据库里面成功保存了实体以及关系，但是提问时，任何问题都会返回这个报错。

抽取的是长篇中文小说

**Comment by Tian-ye1214** [comment]
测试了3本中长小说，大概都是100W字左右的量级，可能是prompt太长了，超出了LLM的上下文本长度，在naive模式下有回答，但切换到其他3个模式就没有了。请问这一点是否能够改进？

**Comment by LarFii** [comment]
可以切换成mini，turbo确实会有这个问题，同时可以修改query param中的topk，减小k值也能解决这个问题。后续我们会考虑更好的办法来限制上下文长度。
