### ISSUE TITLE
请问可以添加ollama模型吗

### ISSUE THREAD

**Issue by yanning169** [HKUDS/LightRAG#3]

**Comment by LarFii** [comment]
后续经过测试后我们会逐步添加其他模型（包括ollama模型）

**Comment by 2481241414** [comment]
> 后续经过测试后我们会逐步添加其他模型（包括ollama模型）

期待更新

**Comment by LarFii** [comment]
新的源码已经提供Ollama支持，可以尝试一下（有些未知bug需要逐步修复）
