### ISSUE TITLE
查询时有问题

### ISSUE THREAD

**Issue by hznnnnnn** [HKUDS/LightRAG#31]
当我在进行global查询的时候：
Traceback (most recent call last):
  File "D:\workspace\LightRAG-main\test.py", line 27, in <module>
    print(rag.query("唐三的武魂是什么?", param=QueryParam(mode="global")))
  File "D:\workspace\LightRAG-main\lightrag\lightrag.py", line 310, in query
    return loop.run_until_complete(self.aquery(query, param))
  File "C:\Users\Kayn\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\workspace\LightRAG-main\lightrag\lightrag.py", line 324, in aquery
    response = await global_query(
  File "D:\workspace\LightRAG-main\lightrag\operate.py", line 686, in global_query
    context = await _build_global_query_context(
  File "D:\workspace\LightRAG-main\lightrag\operate.py", line 727, in _build_global_query_context
    *[knowledge_graph_inst.get_edge(r["src_id"], r["tgt_id"]) for r in results]
  File "D:\workspace\LightRAG-main\lightrag\operate.py", line 727, in <listcomp>
    *[knowledge_graph_inst.get_edge(r["src_id"], r["tgt_id"]) for r in results]
KeyError: 'src_id'

当我在进行local查询的时候也报错，再node_datas = await asyncio.gather(
        *[knowledge_graph_inst.get_node(r["entity_name"]) for r in results]
    )的时候无法找到entity_name

这是我在构建的时候出现了什么问题吗？我构建完成后运行的开始输出如下：
INFO:lightrag:Load KV full_docs with 1 data
INFO:lightrag:Load KV text_chunks with 86 data
INFO:lightrag:Load KV llm_response_cache with 175 data
INFO:lightrag:Loaded graph from ./test\graph_chunk_entity_relation.graphml with 155 nodes, 103 edges
INFO:nano-vectordb:Load (10, 768) data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './test\\vdb_entities.json'} 10 data
INFO:nano-vectordb:Load (103, 768) data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './test\\vdb_relationships.json'} 103 data
INFO:nano-vectordb:Load (86, 768) data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './test\\vdb_chunks.json'} 86 data
WARNING:lightrag:All docs are already in the storage
INFO:lightrag:Writing graph with 155 nodes, 103 edges

**Comment by LarFii** [comment]
具体使用的是什么模型，能顺便给我一份测试使用的文本吗

**Comment by hznnnnnn** [comment]
> 具体使用的是什么模型，能顺便给我一份测试使用的文本吗

我使用的模型是qwen2.5:14b和nomic-embed-text，使用的文档如下：
[test.txt](https://github.com/user-attachments/files/17408990/test.txt)
生成的文件如下：

**Comment by hznnnnnn** [comment]
> 具体使用的是什么模型，能顺便给我一份测试使用的文本吗

[test.zip](https://github.com/user-attachments/files/17409012/test.zip)

**Comment by hznnnnnn** [comment]
> 具体使用的是什么模型，能顺便给我一份测试使用的文本吗

生成的时候调用本地ollama的部分代码是我自己修改的，但是是能正确运行完整个工作流的

**Comment by hznnnnnn** [comment]
> 最新的代码里面修改了Ollama的部分，并且我尝试了Qwen2.5 7b和Llama3.1 8b都可以正常运行。如果默认设置不行，需要减少prompt.py中的example数量以及减小chunk size。

我的问题出在operate.py中的*[knowledge_graph_inst.get_edge(r["src_id"], r["tgt_id"]) for r in results]，我的results中并没有src_id这个参数，我不知道是不是我构建的时候文件的输出格式有问题，所以我也把我构建好后的文件在上面放出来了（test.zip）

**Comment by LarFii** [comment]
我检查一下似乎是存储的时候出了问题，建议清除所有的缓存重新尝试一下
