### ISSUE TITLE
batch size is invalid, it should not be larger than 25.

### ISSUE THREAD

**Issue by yslion** [HKUDS/LightRAG#319]
openai.BadRequestError: Error code: 400 - {'error': {'code': 'InvalidParameter', 'param': None, 'message': 'batch size is invalid, it should not be larger than 25.: payload.input.contents', 'type': 'InvalidParameter'}, 'id': 'ce6c0c89-a338-9df8-afa8-acbd4d544f35', 'request_id': 'ce6c0c89-a338-9df8-afa8-acbd4d544f35'}

**Comment by houxilong** [comment]
same problems,how did you solve it.

**Comment by chandasampath** [comment]
Is there a direct integration to OpenAI Batch with LightRAG?

**Comment by yslion** [comment]
> same problems,how did you solve it.

embedding 用了千问的text-embedding-v2，这玩意不行。openai的原版是没问题的。最后换了豆包家的好了

**Comment by houxilong** [comment]
Qwen2 text-embedding-V2 support batch size is 25, so add parameter "embedding_batch_num" to 25, as follows:

`        rag = LightRAG(
            working_dir=WORKING_DIR,
            llm_model_func=llm_model_func,
            embedding_func=EmbeddingFunc(
                embedding_dim=1536,
                max_token_size=8192,
                func=embedding_func,
                embedding_batch_num=25
            )`

**Comment by yaohanze** [comment]
> Qwen2 text-embedding-V2 support batch size is 25, so add parameter "embedding_batch_num" to 25, as follows:
> 
> ` rag = LightRAG( working_dir=WORKING_DIR, llm_model_func=llm_model_func, embedding_func=EmbeddingFunc( embedding_dim=1536, max_token_size=8192, func=embedding_func, embedding_batch_num=25 )`

embedding_batch_number should be a parameter of LightRAG instead of EmbeddingFunc.
