### ISSUE TITLE
__init__() got an unexpected keyword argument 'kg' Error in LightRAG Initialization

### ISSUE THREAD

**Issue by aaqib-ahmed-nazir** [HKUDS/LightRAG#334]
When initializing the LightRAG class, an error occurs indicating that the kg keyword argument is unexpected. This prevents the application from running as intended. I am trying to integrate neo4j, same approach is used in the example file in the repo however its giving an error. 

- Code Snippet:

```py 
WORKING_DIR = "./local_neo4jWorkDir"

rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=llm_model_func,
    kg="Neo4JStorage", 
    log_level="INFO"  
)

```

- Error Message:
```bash 
An error occurred: LightRAG.__init__() got an unexpected keyword argument 'kg'
```

**Comment by DW934** [comment]
+1

**Comment by DW934** [comment]
1.将“kg”修改为“graph_storage”：
rag = LightRAG(
working_dir=WORKING_DIR,
graph_storage="Neo4JStorage",
log_level="INFO",
...
)
2.在Class LightRAG中，注释掉embedding_func:
self.chunk_entity_relation_graph = self.graph_storage_cls(
namespace="chunk_entity_relation",
global_config=asdict(self),
# embedding_func=self.embedding_func,
)

**Comment by Arslan-Mehmood1** [comment]
There is no parameter 'kg' for class LightRAG.

use argument : graph_storage = 'Neo4JStorage'

![image](https://github.com/user-attachments/assets/7ec6b8f7-64ed-4133-b8bb-ae0f765ad3c0)

![image](https://github.com/user-attachments/assets/d67f787f-238b-44e7-95a8-7cbb6820d1bd)

**Comment by aaqib-ahmed-nazir** [comment]
Thanks alot :)
