### ISSUE TITLE
Unable to run the file lightrag_oracle_demo.py

### ISSUE THREAD

**Issue by ramiroortiz** [HKUDS/LightRAG#337]
I was able to run the demo that uses the openai services lightrag_openai_compatible_demo.py but when I run the file  lightrag_oracle_demo.py the process hangs at 12% of the entity identification. I got the following error:
INFO:lightrag:Node and edge data had been saved into oracle db already, so nothing to do here!
An error occurred: Error code: 500 - {'detail': '{\'target_service\': \'generative_ai_inference\', \'status\': 400, \'code\': \'400\', \'opc-request-id\': \'B0D3887E455841B5A4550F9A5E976B23/5C7AAC456AA93EC4F19CCE61DB2D9BCC/DC64FD2C8DB3E80CFC36EE0C0FB8B01C\', \'message\': \'Inappropriate output content detected in output blocklist\', \'operation_name\': \'chat\', \'timestamp\': \'2024-11-27T23:20:47.429929+00:00\', \'client_version\': \'Oracle-PythonSDK/2.139.0\', \'request_endpoint\': \'POST https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/20231130/actions/chat\', \'logging_tips\': \'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.\', \'troubleshooting_tips\': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_400__400_400 for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/generative-ai-inference/20231130/ChatResult/Chat for details on this operation\'s requirements. If you are unable to resolve this generative_ai_inference issue, please contact Oracle support and provide them this full error message."}'}
![Captura de pantalla 2024-11-27 200456](https://github.com/user-attachments/assets/5dcd051c-d262-4410-8f7d-18d7dd9c1769)

Please help me. Thanks.

**Comment by jin38324** [comment]
That error message if from OCI Generative AI service.
Actually, it's not really an error. This appears because the AI output text contains some inappropriate content, such as violence, discrimination, etc.
To avoid this, try to check your document content first.

**Comment by ramiroortiz** [comment]
Thanks for your help
