### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by guanzy2012** [HKUDS/LightRAG#34]
INFO:lightrag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
  File "D:/RAG/LightRAG-main/test.py", line 19, in <module>
    rag.insert(f.read())
  File "D:\RAG\LightRAG-main\lightrag\lightrag.py", line 177, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "D:\anaconda\envs\llm\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\RAG\LightRAG-main\lightrag\lightrag.py", line 222, in ainsert
    await self.chunks_vdb.upsert(inserting_chunks)
  File "D:\RAG\LightRAG-main\lightrag\storage.py", line 103, in upsert
    results = self._client.upsert(datas=list_data)
  File "D:\anaconda\envs\llm\lib\site-packages\nano_vectordb\dbs.py", line 92, in upsert
    self.__storage["matrix"][i] = update_d[f_VECTOR].astype(Float)
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by 7231959** [comment]
我也遇到了类似问题 发生异常: IndexError
index 0 is out of bounds for axis 0 with size 0
  File "/docker/LightRAG/lightrag/storage.py", line 102, in upsert
    results = self._client.upsert(datas=list_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/docker/LightRAG/lightrag/lightrag.py", line 210, in ainsert
    await self.chunks_vdb.upsert(inserting_chunks)
  File "/docker/LightRAG/lightrag/lightrag.py", line 166, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/docker/LightRAG/lightrag_openai_compatible_demo.py", line 60, in <module>
    rag.insert(text)
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by syogesh18** [comment]
Are you guys re inserting or does this error occur for the first time insertion ?

**Comment by guanzy2012** [comment]
This error occur for the first time insertion,

**Comment by LarFii** [comment]
We've never encountered this issue before. Could you please provide a more detailed description of the problem?

**Comment by guanzy2012** [comment]
between entity extraction and embedding of the chunks, this issue occurs.
INFO:lightrag:Logger initialized for working directory: ./dickens
DEBUG:lightrag:LightRAG init with param:
  working_dir = ./dickens,
  chunk_token_size = 1200,
  chunk_overlap_token_size = 100,
  tiktoken_model_name = gpt-4o-mini,
  entity_extract_max_gleaning = 1,
  entity_summary_to_max_tokens = 500,
  node_embedding_algorithm = node2vec,
  node2vec_params = {'dimensions': 1536, 'num_walks': 10, 'walk_length': 40, 'window_size': 2, 'iterations': 3, 'random_seed': 3},
  embedding_func = {'embedding_dim': 1536, 'max_token_size': 8192, 'func': <function openai_embedding at 0x00000253334AA3B0>},
  embedding_batch_num = 32,
  embedding_func_max_async = 16,
  llm_model_func = <function azure_gpt_4o_mini_complete at 0x00000253334A9F30>,
  llm_model_name = azure02-gpt-4o-mini,
  llm_model_max_token_size = 32768,
  llm_model_max_async = 16,
  key_string_value_json_storage_cls = <class 'lightrag.storage.JsonKVStorage'>,
  vector_db_storage_cls = <class 'lightrag.storage.NanoVectorDBStorage'>,
  vector_db_storage_cls_kwargs = {},
  graph_storage_cls = <class 'lightrag.storage.NetworkXStorage'>,
  enable_llm_cache = True,
  addon_params = {},
  convert_response_to_json_func = <function convert_response_to_json at 0x000002533349BB50>
INFO:lightrag:Load KV full_docs with 0 data
INFO:lightrag:Load KV text_chunks with 0 data
INFO:lightrag:Load KV llm_response_cache with 0 data
INFO:lightrag:Loaded graph from ./dickens\graph_chunk_entity_relation.graphml with 0 nodes, 0 edges
INFO:nano-vectordb:Load (0, 1536) data
INFO:nano-vectordb:Init {'embedding_dim': 1536, 'metric': 'cosine', 'storage_file': './dickens\\vdb_entities.json'} 0 data
INFO:nano-vectordb:Load (0, 1536) data
INFO:nano-vectordb:Init {'embedding_dim': 1536, 'metric': 'cosine', 'storage_file': './dickens\\vdb_relationships.json'} 0 data
INFO:nano-vectordb:Load (0, 1536) data
INFO:nano-vectordb:Init {'embedding_dim': 1536, 'metric': 'cosine', 'storage_file': './dickens\\vdb_chunks.json'} 42 data
INFO:lightrag:[New Docs] inserting 1 docs
INFO:lightrag:[New Chunks] inserting 42 chunks
INFO:lightrag:Inserting 42 vectors to chunks
INFO:httpx:HTTP Request: POST https://......./embeddingA/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://......./embeddingA/embeddings "HTTP/1.1 200 OK"
INFO:lightrag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
  File "D:/RAG/LightRAG-main/test.py", line 19, in <module>
    rag.insert(f.read())
  File "D:\RAG\LightRAG-main\lightrag\lightrag.py", line 177, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "D:\anaconda\envs\llm\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\RAG\LightRAG-main\lightrag\lightrag.py", line 222, in ainsert
    await self.chunks_vdb.upsert(inserting_chunks)
  File "D:\RAG\LightRAG-main\lightrag\storage.py", line 103, in upsert
    results = self._client.upsert(datas=list_data)
  File "D:\anaconda\envs\llm\lib\site-packages\nano_vectordb\dbs.py", line 92, in upsert
    self.__storage["matrix"][i] = update_d[f_VECTOR].astype(Float)
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by guanzy2012** [comment]
INFO:lightrag:Writing graph with 0 nodes, 0 edges
I think that this is the crux of the issue.

**Comment by LarFii** [comment]
Based on the log, it seems that the issue occurs right after the embedding phase when attempting to write the data. It's likely that the cache wasn't cleared properly. I recommend creating a new working directory and trying again.

**Comment by Kilimajaro** [comment]
> Based on the log, it seems that the issue occurs right after the embedding phase when attempting to write the data. It's likely that the cache wasn't cleared properly. I recommend creating a new working directory and trying again.

That's right! This step has solved mine~Thanks！
