### ISSUE TITLE
error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 768 and the array at index l has size 1792

### ISSUE THREAD

**Issue by 240839785** [HKUDS/LightRAG#356]
![微信图片_20241130100229](https://github.com/user-attachments/assets/7b830329-602a-4839-b8ff-1a712fdbe79c)
error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 768 and the array at index l has size 1792
Problems with conan embedding model, I've tried it according to the method in issue34, but the problem persists

**Comment by unizhu** [comment]
embedding_dim = 1792

**Comment by 240839785** [comment]
I solved the problem by replacing conan with nomic
