### ISSUE TITLE
Minor enhancement for stability

### ISSUE THREAD

**Issue by arch7tect** [HKUDS/LightRAG#40]
Sometimes the model (Qwen2.5:72b) returns an empty list when extracting entities and relationships. The attached patch allows you to avoid program crashes and skip invalid records.

**Comment by arch7tect** [comment]
[operate.txt](https://github.com/user-attachments/files/17424059/operate.txt)

**Comment by LarFii** [comment]
Thanks for your contribution! In the next commit, I will include your patch to handle this issue
