### ISSUE TITLE
Can we use external Vector databases and Knowledge graphs other than storing in the json formats?

### ISSUE THREAD

**Issue by ashishjaddu** [HKUDS/LightRAG#42]
Can we use external Vector databases and Knowledge graphs like Pinecone, Neo4j, etc for storing these graphs and embeddings?

**Comment by LarFii** [comment]
Thanks for your attention. We currently don’t offer support for external vector databases, but you can definitely try integrating them.

**Comment by ashishjaddu** [comment]
In order to integrate them, If I play around with the codes in reproduce folder would that be enough?

**Comment by LarFii** [comment]
No, that won’t be enough. If you want to use a different vector database, you’ll need to modify `storage.py`, which is quite a big task. However, after inserting, the resulting graph can be imported into Neo4j. We will be providing support for this in the next couple of days.
