### ISSUE TITLE
中文提示词

### ISSUE THREAD

**Issue by AlexCRX** [HKUDS/LightRAG#43]
能否增加一个官方中文 Prompt 的最佳实践？我自己模仿en_prompt 写的cn_prompt，总是出现问题，且效果不佳。

**Comment by LarFii** [comment]
明白了，后续我们会尽快调试一个合适的中文prompt出来，请继续关注：）

**Comment by small122** [comment]
同求

**Comment by McFly-byte** [comment]
请问出了吗？
