### ISSUE TITLE
How can I get the input chunks as a response in the query function as well?

### ISSUE THREAD

**Issue by kabironline** [HKUDS/LightRAG#44]
My usecase requires me to cite the exact paragraph or at least know what the original text was. Is there any way in the query params where I can change and get the exact chunks as a response as well. I went through the code but couldn't find it.

**Comment by LarFii** [comment]
Your use case seems more suited for a naive query. You can modify the output in the `operate.py` to retrieve the context along with the response.

**Comment by kabironline** [comment]
Sure I will give it a try, might send a pull request because its a very useful feature.
