### ISSUE TITLE
关于单纯使用LightRAG

### ISSUE THREAD

**Issue by joseph16388** [HKUDS/LightRAG#445]
请问如果不用大模型，单纯使用LightRAG分析一个文档实体与实体间、实体与事件、事件与事件的关系，这个可以输出出来吗？

**Comment by magicyuan876** [comment]
提取实体和关系本身就是用LLM来抽取的呀，不用LLM肯定不行呀

**Comment by joseph16388** [comment]
> 提取实体和关系本身就是用LLM来抽取的呀，不用LLM肯定不行呀

好的，3Q
