### ISSUE TITLE
Improve insert speed

### ISSUE THREAD

**Issue by CVHvn** [HKUDS/LightRAG#46]
When I use the default hyperparameters, I see that my GPU only uses 14 to 24 GB of VRAM (I have more VRAM with the A100), and the GPU is not running at full load. Therefore, I think I can improve the entity extraction speed. Do you have any experience in improving entity extraction speed? (maybe I need increase llm_model_max_async or embedding_func_max_async or embedding_batch_num?)

**Comment by LarFii** [comment]
We don't have much experience with local deployment, but you can definitely try adjusting the `llm_model_max_async` or `embedding_func_max_async` parameters to improve the extraction speed.
