### ISSUE TITLE
请问如何控制抽取实体和关系过程中大模型的并发量

### ISSUE THREAD

**Issue by wi162yyxq** [HKUDS/LightRAG#463]
我看代码中用的AsyncOpenAI进行大模型的调用，但是因为目前项目中没有控制并发数量的参数，导致chunk切的多的时候并发量大，计算变慢，大模型长时间无法返回结果导致失败。
我在项目中用semaphore = asyncio.Semaphore(max_concurrent_tasks)增加并发限制，但是并未生效。
请问各位大佬是如何解决这个并发量问题的，如何进行调整。

**Comment by hixulei** [comment]
我这里也遇到了线上api大模型报错的情况，应该是请求过于频繁了。求解。

**Comment by kiss0840** [comment]
默认所有chunk数据一次性处理，批量处理可避免LLM拒载。
方法：修改 operate.py 的 async def extract_entities 方法，将 await asyncio.gather(*task) 进行分批处理：

results = []
    batch_size = global_config["llm_model_max_async"]
    epoch = len(ordered_chunks) // batch_size
    if len(ordered_chunks) % batch_size != 0:
        epoch += 1
    for i in range(epoch):
        start = i * batch_size
        end = (i + 1) * batch_size
        if end > len(ordered_chunks):
            end = len(ordered_chunks)
        ordered_chunks_in_batch = ordered_chunks[start:end]

        task = []
        task.extend([_process_single_content(c) for c in ordered_chunks_in_batch])
        results.extend(
            await asyncio.gather(*task)
        )
