### ISSUE TITLE
Duplicate sections in rag_response prompt

### ISSUE THREAD

**Issue by punkt2** [HKUDS/LightRAG#48]
I noticed that the  "---Goal---" and "---Target response length and format---" sections appear twice in the rag_response  prompt. Is this intended?

https://github.com/HKUDS/LightRAG/blob/e7a7ff62b264ae7dde437c8dac3e32847090805a/lightrag/prompt.py#L156C1-L183C16

**Comment by LarFii** [comment]
That was my oversight, I will fix it right away.
