### ISSUE TITLE
向原知识图谱中加入新数据可能导致 LLM 对旧数据的效果变差怎么解决

### ISSUE THREAD

**Issue by ShayLyu** [HKUDS/LightRAG#519]
向原知识图谱中加入新数据可能导致 LLM 对旧数据的效果变差怎么解决

**Comment by LarFii** [comment]
现在新增了图谱对时序问题的支持，LLM会得到新旧数据插入的时间戳，能够解决一部分问题

**Comment by fengshaoA** [comment]
> 现在新增了图谱对时序问题的支持，LLM会得到新旧数据插入的时间戳，能够解决一部分问题

您好 我最近在使用lightrag时也遇到一个类似的问题 就是我每次插入新文档的时候，模型都需要和之前插入的数据构建关系 但是我已经知道新插入的文档和之前插入的知识并没有关系，我如何控制不让新插入处的文档和之前知识构建关系呢？
