### ISSUE TITLE
合并Entity功能

### ISSUE THREAD

**Issue by Feliks151450** [HKUDS/LightRAG#55]
在看AI生成的实体的时候，发现有很多实际上是同一个概念的东西被识别成很多个实体，只是个别的单词不同而已。能否考虑给一个手动合并实体的功能呢。就是提供一个方法，输入想要合并的实体名和最终合并后的名字，数据库里则把这些实体做一个合并并保存

**Comment by LarFii** [comment]
这确实是个不错的功能，后续我们会加上这个功能，不过目前人力有限可能需要一段时间，敬请期待：）
