### ISSUE TITLE
FYI -  tried a few other models and combinations.  I still do not understand how its possible to work without access to `gpt-4o.mini` in the current codebase (as its used for tokenization).

### ISSUE THREAD

**Issue by Klavdija986** [HKUDS/LightRAG#57]
FYI -  tried a few other models and combinations.  I still do not understand how its possible to work without access to `gpt-4o.mini` in the current codebase (as its used for tokenization).

_Originally posted by @maxruby in https://github.com/HKUDS/LightRAG/issues/30#issuecomment-2418131291_

**Comment by 44cort44** [comment]
> ```
>           FYI -  tried a few other models and combinations.  I still do not understand how its possible to work without access to `gpt-4o.mini` in the current codebase (as its used for tokenization).
> ```
> 
> _Originally posted by @maxruby in [#30 (comment)](https://github.com/HKUDS/LightRAG/issues/30#issuecomment-2418131291)_

https://github.com/HKUDS/LightRAG/blob/main/lightrag/utils.py#L113

This global ENCODER variable is not none, and therefore doesn't use it.

It falls back to "o200k_base".
