### ISSUE TITLE
OpenAI rate limit, how to overcome it?

### ISSUE THREAD

**Issue by Shubh789da** [HKUDS/LightRAG#58]
I am getting below error:

RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-xxxx on tokens per min (TPM): Limit 200000, Used 198355, Requested 4664. Please try again in 905ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Any way to overcome this, I have reduced the document size to 1/20th but still same error. Also I am looking if I can directly create graph as my data is in csv and  I can define the edges, nodes and relationships. So LightRAG can directly get it from the manual create db?

Thanks in advance

**Comment by 44cort44** [comment]
https://learn.microsoft.com/en-us/azure/ai-services/openai/quotas-limits

You'll have to pay for a higher limit.

This is not an issue with this project, but a constraint from Microsoft.

**Comment by 44cort44** [comment]
> Also I am looking if I can directly create graph as my data is in csv and I can define the edges, nodes and relationships. So LightRAG can directly get it from the manual create db?
> 
> Thanks in advance

CSVs are used internally as part of the prompt to the LLM to generate text/response to a query, but not as way to load data into the databases.

See here: https://github.com/HKUDS/LightRAG/blob/main/lightrag/operate.py#L756

**Comment by Soumil32** [comment]
I used a library such as aiolimiter and built my own wrapper around the standard openai implementation.
```python
from aiolimiter import AsyncLimiter
from lightrag.llm import openai_complete_if_cache

async def openai_complete_if_cache_rate_limited(rate_limiter: AsyncLimiter, **kwargs):
    async with rate_limiter:
        return await openai_complete_if_cache(**kwargs)
```
