### ISSUE TITLE
Ollama extraction entity not working

### ISSUE THREAD

**Issue by ilanb** [HKUDS/LightRAG#59]
Hi,

How model use for entity extraction ? tried llama3.1 with mxbai-embed-large or llama3.2 nothing extarcted :-(
Work fine with openAI...
thanks !

**Comment by 240839785** [comment]
When I use deepseek's API, it works fine, but when I use ollama's qwen2.5, I encounter 0 entities.

**Comment by LarFii** [comment]
Maybe this [comment](https://github.com/HKUDS/LightRAG/issues/30#issuecomment-2421647020) can help.

**Comment by 240839785** [comment]
> Maybe this [comment](https://github.com/HKUDS/LightRAG/issues/30#issuecomment-2421647020) can help.

yes, i had tried and it works
