### ISSUE TITLE
Embeddings with ndim != 4096

### ISSUE THREAD

**Issue by Florents-Tselai** [HKUDS/LightRAG#60]
I'm having trouble running this with embedding funcs with `ndim != 4096`.

So tying this with 

```python3
rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=llm_model_func,
    embedding_func=EmbeddingFunc(
        embedding_dim=768, max_token_size=8192, func=embedding_func
    ),
)
```

I keep getting

```
venv/lib/python3.12/site-packages/nano_vectordb/dbs.py", line 71, in __post_init__
    storage["embedding_dim"] == self.embedding_dim
AssertionError: Embedding dim mismatch, expected: 768, but loaded: 4096
```

Is this `4096` somehow a magic number?

**Comment by cortseverns** [comment]
> I'm having trouble running this with embedding funcs with `ndim != 4096`.
> 
> So tying this with
> 
> ```python
> rag = LightRAG(
>     working_dir=WORKING_DIR,
>     llm_model_func=llm_model_func,
>     embedding_func=EmbeddingFunc(
>         embedding_dim=768, max_token_size=8192, func=embedding_func
>     ),
> )
> ```
> 
> I keep getting
> 
> ```
> venv/lib/python3.12/site-packages/nano_vectordb/dbs.py", line 71, in __post_init__
>     storage["embedding_dim"] == self.embedding_dim
> AssertionError: Embedding dim mismatch, expected: 768, but loaded: 4096
> ```
> 
> Is this `4096` somehow a magic number?

Different embedding models have different defaults. Have you changed away from nomic-embed-text?

**Comment by Florents-Tselai** [comment]
> > I'm having trouble running this with embedding funcs with `ndim != 4096`.
> > So tying this with
> > ```python
> > rag = LightRAG(
> >     working_dir=WORKING_DIR,
> >     llm_model_func=llm_model_func,
> >     embedding_func=EmbeddingFunc(
> >         embedding_dim=768, max_token_size=8192, func=embedding_func
> >     ),
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I keep getting
> > ```
> > venv/lib/python3.12/site-packages/nano_vectordb/dbs.py", line 71, in __post_init__
> >     storage["embedding_dim"] == self.embedding_dim
> > AssertionError: Embedding dim mismatch, expected: 768, but loaded: 4096
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this `4096` somehow a magic number?
> 
> Different embedding models have different defaults. Have you changed away from nomic-embed-text?

That's what the `embedding_dim` is supposed to set I assume 
```
embedding_func=EmbeddingFunc(
        embedding_dim=768, max_token_size=8192, func=embedding_func
    )
```

**Comment by Florents-Tselai** [comment]
* and yes, I got the same error when I tried an embedding model with `embedding_dim=2048` for example.

**Comment by LarFii** [comment]
The embedding model's dimension should match the one you've set. I suggest you try setting `embedding_dim=4096` and see if that works : ).

**Comment by Florents-Tselai** [comment]
> The embedding model's dimension should match the one you've set. I suggest you try setting `embedding_dim=4096` and see if that works : ).

Why would I do that ? 
I know my embedding model it's not 4096.
Anyway I tried that and again it doesn't work.

Looks like whatever the embedding model ndim is, from the storage layer it tries to fetch vectors with ndim=4096

**Comment by boogle** [comment]
把你WORKING_DIR目录下，生成的配置文件删除后，重新运行即可。

**Comment by LarFii** [comment]
> > The embedding model's dimension should match the one you've set. I suggest you try setting `embedding_dim=4096` and see if that works : ).
> 
> Why would I do that ? I know my embedding model it's not 4096. Anyway I tried that and again it doesn't work.
> 
> Looks like whatever the embedding model ndim is, from the storage layer it tries to fetch vectors with ndim=4096

One potential solution is to create a new working directory and try again. If this doesn't work, please provide the specific log and more detailed information about the runtime environment.

**Comment by thinkthinking** [comment]
> 把你WORKING_DIR目录下，生成的配置文件删除后，重新运行即可。

it works, thank you
