### ISSUE TITLE
已经搭建好了ollama服务器，怎么在lightrag里面设置，可以使用ollama的llm和embedding模型

### ISSUE THREAD

**Issue by leon202406** [HKUDS/LightRAG#66]
已经搭建好了ollama服务器，怎么在lightrag里面设置，可以使用ollama的llm和embedding模型。
谢谢！

**Comment by LarFii** [comment]
可以参考example里面的demo，以及readme的里的Ollama模型使用

**Comment by leon202406** [comment]
里面没有配置信息，或者你们的配置文件模板是否可以提供一下。谢谢！

**Comment by leon202406** [comment]
就是使用lightrag_ollama_demo.py进行验证测试，不太清楚在哪里设置ollama服务。谢谢！

**Comment by LarFii** [comment]
这个属于Ollama服务部署的问题，只要正常启动即可，可以查查相关的方案，我手边暂时没有可用的搭建好Ollama的服务器 : (

**Comment by sparkyqin** [comment]
楼主的意思是如何设置ollama服务的url，demo中貌似直接指定了模型名称，应该是默认使用了本地ollama模型，无法指定远端ollama的url

**Comment by Frty47222** [comment]
> 楼主的意思是如何设置ollama服务的url，demo中貌似直接指定了模型名称，应该是默认使用了本地ollama模型，无法指定远端ollama的url

mark

**Comment by zydmtaichi** [comment]
本地的ollama也无法结合lightrag使用，这个项目存在严重问题

**Comment by zhanglaplace** [comment]
> 本地的ollama也无法结合lightrag使用，这个项目存在严重问题

这边用ollama api的形式看着是没啥问题

**Comment by zydmtaichi** [comment]
> > 本地的ollama也无法结合lightrag使用，这个项目存在严重问题
> 
> 这边用ollama api的形式看着是没啥问题

见[该issue](https://github.com/HKUDS/LightRAG/issues/162)，在替换embed模型为nomic-embed-text后可以跑通，其余除dim外无修改，跑通后回复均为”Sorry, I'm not able to provide an answer to that question“
