### ISSUE TITLE
中文提示词

### ISSUE THREAD

**Issue by lingyezhixing** [HKUDS/LightRAG#67]
能否添加中文提示词，目前的英文提示词在处理中文时大部分情况下也能有不错的效果，但是在使用本地小模型比如Qwen2.5-7B-Instruct和Qwen2.5-3B-Instruct时出现了遗漏信息的情况，可能是小模型能力本来就不强再加跨语言就会出问题，我自己改的中文提示词效果并不好，有时会出现一些莫名其妙的问题。

**Comment by LarFii** [comment]
中文提示词也是我们后续工作之一，但是由于人手有限可能需要一定时间。在index阶段，更大的影响因素还是模型本身的能力，哪怕是4o和mini差距也巨大，所以更换提示词很可能不能起到预期的效果。
