### ISSUE TITLE
Problem in running

### ISSUE THREAD

**Issue by karimibrahimmustafa** [HKUDS/LightRAG#68]
It keeps giving me that error when using hf model. 
With the given book and snips of code in the readme file
![image](https://github.com/user-attachments/assets/e5dbe5be-eb8e-4baa-8774-ff4dcb5c6806)

**Comment by LarFii** [comment]
You can try clearing all cache files and run the process again. If the issue persists, please provide the specific log and more detailed information about the runtime environment.
