### ISSUE TITLE
How to do RAG without embedding

### ISSUE THREAD

**Issue by MonolithFoundation** [HKUDS/LightRAG#7]
How to do RAG without embedding

**Comment by HKUDS** [comment]
Thank you for your interest! Conducting the retrieval process using vectors may be more efficient.

**Comment by MonolithFoundation** [comment]
Due to computational constraints, I am unable to set up an embedding model. In this situation, is it possible to perform Retrieval-Augmented Generation (RAG) only with graph RAG? Performance is not considered here. If so, how can it be done?

**Comment by LarFii** [comment]
The embedding model is necessary for LightRAG because embeddings represent the contexts and queries in a way that enables efficient retrieval. However, if you face computational constraints, you can use external APIs for embeddings, avoiding deploying models locally.
