### ISSUE TITLE
对接阿里通义千问大模型API

### ISSUE THREAD

**Issue by joseph16388** [HKUDS/LightRAG#72]
请问如何对接阿里通义千问大模型API，谢谢！
PS：和OPENAI API KEY类似是在线官网的API KEY

**Comment by LarFii** [comment]
可以参考examples下面的[lightrag_openai_compatible_demo.py](https://github.com/HKUDS/LightRAG/blob/main/examples/lightrag_openai_compatible_demo.py)

**Comment by joseph16388** [comment]
> 可以参考examples下面的[lightrag_openai_compatible_demo.py](https://github.com/HKUDS/LightRAG/blob/main/examples/lightrag_openai_compatible_demo.py)

好的，我先试试哈！
