### ISSUE TITLE
Search Speed Optimization with Caching 

### ISSUE THREAD

**Issue by himanshukumaaar** [HKUDS/LightRAG#74]
Hii @LarFii 

I've a suggestion to enhance query response speed, you can implement caching using Redis. The process involves checking if a query result is already stored in Redis. If found, the cached result is returned instantly. If not, the query is processed, and the result is cached for future use. You can set expiration times (e.g. 10 minutes) to keep the cache fresh. This reduces redundant database/API calls, improving performance for frequently used queries.

Structure:

- Check cache.
- If not found, retrieve from the database.
- Cache the result.

**Comment by LarFii** [comment]
Thank you very much for your suggestion! We actually already have a caching mechanism in place, though it doesn't currently include expiration. This is implemented by [nano-graphrag](https://github.com/gusye1234/nano-graphrag). We will definitely consider adding an expiration setting in the future. Thanks again!

**Comment by SairoUltraman** [comment]
> Thank you very much for your suggestion! We actually already have a caching mechanism in place, though it doesn't currently include expiration. This is implemented by [nano-graphrag](https://github.com/gusye1234/nano-graphrag). We will definitely consider adding an expiration setting in the future. Thanks again!

Hi man.Using Redis as kv_storage is currently the best solution for concurrent scenarios. Do you have any plans to implement it recently?
