### ISSUE TITLE
How to run on csv data

### ISSUE THREAD

**Issue by NIHALPATTANSHETTY** [HKUDS/LightRAG#80]
Every single example is written for text input, but if a user wants to test it on csv data, how should he proceed? 

In the MS Graphrag, they have a settings.yaml file which can be changed to accept csv data.

Also, in csv data, how do you change the entity type to take custom entity which the LLM might not know, for example : order number

**Comment by LarFii** [comment]
At the moment, you can only read the CSV file as a string and insert it. If you need to modify the entity types, you can edit the `lightrag/prompt.py` and modify [`PROMPTS["DEFAULT_ENTITY_TYPES"] = ["organization", "person", "geo", "event"]`](https://github.com/HKUDS/LightRAG/blob/5e388f3f9fd8c3bb8b326ac2031ac00fbb392101/lightrag/prompt.py#L10C1-L10C77) to include your custom entity types.
