### ISSUE TITLE
自定义实体列表和中文提示词支持

### ISSUE THREAD

**Issue by xufengnian** [HKUDS/LightRAG#89]
你好，lightrag使用过程中，希望可以类似graphrag支持自定义实体列表和中文提示词，这样抽取的实体结果可能更加符合实际使用，非常感谢

**Comment by supdizh** [comment]
+1

**Comment by LarFii** [comment]
实体列表现在可以通过修改`lightrag/prompt.py`中的[第10行](https://github.com/HKUDS/LightRAG/blob/5e388f3f9fd8c3bb8b326ac2031ac00fbb392101/lightrag/prompt.py#L10C1-L10C77)完成，中文提示词可能还需要一定时间。

**Comment by xufengnian** [comment]
> 实体列表现在可以通过修改`lightrag/prompt.py`中的[第10行](https://github.com/HKUDS/LightRAG/blob/5e388f3f9fd8c3bb8b326ac2031ac00fbb392101/lightrag/prompt.py#L10C1-L10C77)完成，中文提示词可能还需要一定时间。

自己改第10行，也是一个固定值，不方便，这两个我自己实现了一下，自定义提示词+中文prompt，说下我的思路供参考

一、自定义实体非常简单，目前operate.py里写死的，现在改成可以获取动态值
![image](https://github.com/user-attachments/assets/3d56f44d-70c1-42d7-8655-aa90e754e340)

二、中文prompt两个做法：
1.复杂点：如果你的输入语言五花八门，参考graphrag来个prompt.tune支持指定语言
2.简单点：如果你的输入基本就中文，那修改一下prompt.py，把提取实体/关系的提示词和样例改成Chinest和中文示例
效果挺好的
自己简单做的UI页面，生成的查询图谱效果已经从原先的英文变中文了
![image](https://github.com/user-attachments/assets/8930b941-9611-4420-b10e-e86ae0c252a8)

**Comment by smileyee** [comment]
> > 实体列表现在可以通过修改`lightrag/prompt.py`中的[第10行](https://github.com/HKUDS/LightRAG/blob/5e388f3f9fd8c3bb8b326ac2031ac00fbb392101/lightrag/prompt.py#L10C1-L10C77)完成，中文提示词可能还需要一定时间。
> 
> 自己改第10行，也是一个固定值，不方便，这两个我自己实现了一下，自定义提示词+中文prompt，说下我的思路供参考
> 
> 一、自定义实体非常简单，目前operate.py里写死的，现在改成可以获取动态值 ![image](https://private-user-images.githubusercontent.com/15324125/379661315-3d56f44d-70c1-42d7-8655-aa90e754e340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTU2NDIsIm5iZiI6MTczMDQ1NTM0MiwicGF0aCI6Ii8xNTMyNDEyNS8zNzk2NjEzMTUtM2Q1NmY0NGQtNzBjMS00MmQ3LTg2NTUtYWE5MGU3NTRlMzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwMDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NTczYTYwODM4ZTk3OTkyYmFmYmUyNzQ5MzcyNzNhOTdkNjFkNTQ5ZGI4ODM0MmJjZjkyZjQ5YTY4MjY3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZrGVL5c_kH3wvTLDBDOewpQOLU73jgMwdGIltkbybtc)
> 
> 二、中文prompt两个做法： 1.复杂点：如果你的输入语言五花八门，参考graphrag来个prompt.tune支持指定语言 2.简单点：如果你的输入基本就中文，那修改一下prompt.py，把提取实体/关系的提示词和样例改成Chinest和中文示例 效果挺好的 自己简单做的UI页面，生成的查询图谱效果已经从原先的英文变中文了 ![image](https://private-user-images.githubusercontent.com/15324125/379661649-8930b941-9611-4420-b10e-e86ae0c252a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTU2NDIsIm5iZiI6MTczMDQ1NTM0MiwicGF0aCI6Ii8xNTMyNDEyNS8zNzk2NjE2NDktODkzMGI5NDEtOTYxMS00NDIwLWIxMGUtZTg2YWUwYzI1MmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwMDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OGExOGY2ZTcwNDBlZmQ3N2I5YTVjNDU3NzA4ZTc3NzhkY2VjNzNlYTJlZTExZjgxMDM1MWE1ZjQwZmE1OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u7Y7oI5AyScE6Sc66rvFlK9fJuShaJO5eWhwyYntLfQ)



> > 实体列表现在可以通过修改`lightrag/prompt.py`中的[第10行](https://github.com/HKUDS/LightRAG/blob/5e388f3f9fd8c3bb8b326ac2031ac00fbb392101/lightrag/prompt.py#L10C1-L10C77)完成，中文提示词可能还需要一定时间。
> 
> 自己改第10行，也是一个固定值，不方便，这两个我自己实现了一下，自定义提示词+中文prompt，说下我的思路供参考
> 
> 一、自定义实体非常简单，目前operate.py里写死的，现在改成可以获取动态值 ![image](https://private-user-images.githubusercontent.com/15324125/379661315-3d56f44d-70c1-42d7-8655-aa90e754e340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTU2NDIsIm5iZiI6MTczMDQ1NTM0MiwicGF0aCI6Ii8xNTMyNDEyNS8zNzk2NjEzMTUtM2Q1NmY0NGQtNzBjMS00MmQ3LTg2NTUtYWE5MGU3NTRlMzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwMDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NTczYTYwODM4ZTk3OTkyYmFmYmUyNzQ5MzcyNzNhOTdkNjFkNTQ5ZGI4ODM0MmJjZjkyZjQ5YTY4MjY3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZrGVL5c_kH3wvTLDBDOewpQOLU73jgMwdGIltkbybtc)
> 
> 二、中文prompt两个做法： 1.复杂点：如果你的输入语言五花八门，参考graphrag来个prompt.tune支持指定语言 2.简单点：如果你的输入基本就中文，那修改一下prompt.py，把提取实体/关系的提示词和样例改成Chinest和中文示例 效果挺好的 自己简单做的UI页面，生成的查询图谱效果已经从原先的英文变中文了 ![image](https://private-user-images.githubusercontent.com/15324125/379661649-8930b941-9611-4420-b10e-e86ae0c252a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTU2NDIsIm5iZiI6MTczMDQ1NTM0MiwicGF0aCI6Ii8xNTMyNDEyNS8zNzk2NjE2NDktODkzMGI5NDEtOTYxMS00NDIwLWIxMGUtZTg2YWUwYzI1MmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwMDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OGExOGY2ZTcwNDBlZmQ3N2I5YTVjNDU3NzA4ZTc3NzhkY2VjNzNlYTJlZTExZjgxMDM1MWE1ZjQwZmE1OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u7Y7oI5AyScE6Sc66rvFlK9fJuShaJO5eWhwyYntLfQ)

你好可以分享一下你这个根据问题生成图谱视图是怎么做的吗？

**Comment by geigeqiutoulan** [comment]
哇塞，这个可视化界面太棒了，可以分享一下吗？非常感谢

**Comment by Wenshaunglu** [comment]
这个前端开源不

**Comment by mylovexx** [comment]
> > > 实体列表现在可以通过修改`lightrag/prompt.py`中的[第10行](https://github.com/HKUDS/LightRAG/blob/5e388f3f9fd8c3bb8b326ac2031ac00fbb392101/lightrag/prompt.py#L10C1-L10C77)完成，中文提示词可能还需要一定时间。
> > 
> > 
> > 自己改第10行，也是一个固定值，不方便，这两个我自己实现了一下，自定义提示词+中文prompt，说下我的思路供参考
> > 一、自定义实体非常简单，目前operate.py里写死的，现在改成可以获取动态值 ![image](https://private-user-images.githubusercontent.com/15324125/379661315-3d56f44d-70c1-42d7-8655-aa90e754e340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTU2NDIsIm5iZiI6MTczMDQ1NTM0MiwicGF0aCI6Ii8xNTMyNDEyNS8zNzk2NjEzMTUtM2Q1NmY0NGQtNzBjMS00MmQ3LTg2NTUtYWE5MGU3NTRlMzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwMDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NTczYTYwODM4ZTk3OTkyYmFmYmUyNzQ5MzcyNzNhOTdkNjFkNTQ5ZGI4ODM0MmJjZjkyZjQ5YTY4MjY3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZrGVL5c_kH3wvTLDBDOewpQOLU73jgMwdGIltkbybtc)
> > 二、中文prompt两个做法： 1.复杂点：如果你的输入语言五花八门，参考graphrag来个prompt.tune支持指定语言 2.简单点：如果你的输入基本就中文，那修改一下prompt.py，把提取实体/关系的提示词和样例改成Chinest和中文示例 效果挺好的 自己简单做的UI页面，生成的查询图谱效果已经从原先的英文变中文了 ![image](https://private-user-images.githubusercontent.com/15324125/379661649-8930b941-9611-4420-b10e-e86ae0c252a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTU2NDIsIm5iZiI6MTczMDQ1NTM0MiwicGF0aCI6Ii8xNTMyNDEyNS8zNzk2NjE2NDktODkzMGI5NDEtOTYxMS00NDIwLWIxMGUtZTg2YWUwYzI1MmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwMDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OGExOGY2ZTcwNDBlZmQ3N2I5YTVjNDU3NzA4ZTc3NzhkY2VjNzNlYTJlZTExZjgxMDM1MWE1ZjQwZmE1OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u7Y7oI5AyScE6Sc66rvFlK9fJuShaJO5eWhwyYntLfQ)
> 
> > > 实体列表现在可以通过修改`lightrag/prompt.py`中的[第10行](https://github.com/HKUDS/LightRAG/blob/5e388f3f9fd8c3bb8b326ac2031ac00fbb392101/lightrag/prompt.py#L10C1-L10C77)完成，中文提示词可能还需要一定时间。
> > 
> > 
> > 自己改第10行，也是一个固定值，不方便，这两个我自己实现了一下，自定义提示词+中文prompt，说下我的思路供参考
> > 一、自定义实体非常简单，目前operate.py里写死的，现在改成可以获取动态值 ![image](https://private-user-images.githubusercontent.com/15324125/379661315-3d56f44d-70c1-42d7-8655-aa90e754e340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTU2NDIsIm5iZiI6MTczMDQ1NTM0MiwicGF0aCI6Ii8xNTMyNDEyNS8zNzk2NjEzMTUtM2Q1NmY0NGQtNzBjMS00MmQ3LTg2NTUtYWE5MGU3NTRlMzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwMDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NTczYTYwODM4ZTk3OTkyYmFmYmUyNzQ5MzcyNzNhOTdkNjFkNTQ5ZGI4ODM0MmJjZjkyZjQ5YTY4MjY3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZrGVL5c_kH3wvTLDBDOewpQOLU73jgMwdGIltkbybtc)
> > 二、中文prompt两个做法： 1.复杂点：如果你的输入语言五花八门，参考graphrag来个prompt.tune支持指定语言 2.简单点：如果你的输入基本就中文，那修改一下prompt.py，把提取实体/关系的提示词和样例改成Chinest和中文示例 效果挺好的 自己简单做的UI页面，生成的查询图谱效果已经从原先的英文变中文了 ![image](https://private-user-images.githubusercontent.com/15324125/379661649-8930b941-9611-4420-b10e-e86ae0c252a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTU2NDIsIm5iZiI6MTczMDQ1NTM0MiwicGF0aCI6Ii8xNTMyNDEyNS8zNzk2NjE2NDktODkzMGI5NDEtOTYxMS00NDIwLWIxMGUtZTg2YWUwYzI1MmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwMDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OGExOGY2ZTcwNDBlZmQ3N2I5YTVjNDU3NzA4ZTc3NzhkY2VjNzNlYTJlZTExZjgxMDM1MWE1ZjQwZmE1OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u7Y7oI5AyScE6Sc66rvFlK9fJuShaJO5eWhwyYntLfQ)
> 
> 你好可以分享一下你这个根据问题生成图谱视图是怎么做的吗？



> > 实体列表现在可以通过修改`lightrag/prompt.py`中的[第10行](https://github.com/HKUDS/LightRAG/blob/5e388f3f9fd8c3bb8b326ac2031ac00fbb392101/lightrag/prompt.py#L10C1-L10C77)完成，中文提示词可能还需要一定时间。
> 
> 自己改第10行，也是一个固定值，不方便，这两个我自己实现了一下，自定义提示词+中文prompt，说下我的思路供参考
> 
> 一、自定义实体非常简单，目前operate.py里写死的，现在改成可以获取动态值 ![image](https://github.com/user-attachments/assets/3d56f44d-70c1-42d7-8655-aa90e754e340)
> 
> 二、中文prompt两个做法： 1.复杂点：如果你的输入语言五花八门，参考graphrag来个prompt.tune支持指定语言 2.简单点：如果你的输入基本就中文，那修改一下prompt.py，把提取实体/关系的提示词和样例改成Chinest和中文示例 效果挺好的 自己简单做的UI页面，生成的查询图谱效果已经从原先的英文变中文了 ![image](https://github.com/user-attachments/assets/8930b941-9611-4420-b10e-e86ae0c252a8)

可以分享一下中文提示词吗？谢谢

**Comment by zkailinzhang** [comment]
可以分享一下中文提示词吗？谢谢
