### ISSUE TITLE
Seperate nano vector DB from LightRAG (hosting solution)

### ISSUE THREAD

**Issue by Yazington** [HKUDS/LightRAG#90]
nano vector db runs in memory just like any db. Its better to have it seperated from LightRAG because we need to host the DB and use LightRAG as a library. LightRAG should be stateless and lightweight..

Im not sure if nano vector db is actually stateless

**Comment by LarFii** [comment]
We're working on it—stay tuned!

**Comment by wiltshirek** [comment]
Will what you are working on include integrations for alternative vector and graph solutions, preferably hosted (neo4j and pinecone).  Sorry for the similar qry on separate threads.  Happy to pick this up and contribute since its a feature we'll need to take this to prod.
