### ISSUE TITLE
Not running in EXTERNAL GPU

### ISSUE THREAD

**Issue by Shyamnath-Sankar** [HKUDS/LightRAG#92]
As i am performing LightRag in Ollama there is no gpu usage 
![Screenshot 2024-10-22 105610](https://github.com/user-attachments/assets/0a28be30-999a-462c-8bf6-9dc009f1fed8)

**Comment by TerraceCN** [comment]
check ollama documentation
https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#nvidia-gpu-discovery
https://github.com/ollama/ollama/blob/main/docs/gpu.md
