### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DayanaYuan** [HKUDS/LightRAG#95]
/home/horanchen/anaconda3/envs/lightrag/bin/python /home/horanchen/ydy/study/code/LightRAG/examples/lightrag_hf_demo.py
INFO:lightrag:Logger initialized for working directory: ./dickens
DEBUG:lightrag:LightRAG init with param:
  working_dir = ./dickens,
  chunk_token_size = 1200,
  chunk_overlap_token_size = 100,
  tiktoken_model_name = gpt-4o-mini,
  entity_extract_max_gleaning = 1,
  entity_summary_to_max_tokens = 500,
  node_embedding_algorithm = node2vec,
  node2vec_params = {'dimensions': 1536, 'num_walks': 10, 'walk_length': 40, 'window_size': 2, 'iterations': 1, 'random_seed': 3},
  embedding_func = {'embedding_dim': 384, 'max_token_size': 1000, 'func': <function <lambda> at 0x7c8bd0bf7010>},
  embedding_batch_num = 32,
  embedding_func_max_async = 16,
  llm_model_func = <function hf_model_complete at 0x7c8ace6c1510>,
  llm_model_name = /home/horanchen/ydy/study/code/LightRAG/examples/meta-llama/Llama3-8B-instruct,
  llm_model_max_token_size = 32768,
  llm_model_max_async = 16,
  key_string_value_json_storage_cls = <class 'lightrag.storage.JsonKVStorage'>,
  vector_db_storage_cls = <class 'lightrag.storage.NanoVectorDBStorage'>,
  vector_db_storage_cls_kwargs = {},
  graph_storage_cls = <class 'lightrag.storage.NetworkXStorage'>,
  enable_llm_cache = True,
  addon_params = {},
  convert_response_to_json_func = <function convert_response_to_json at 0x7c8ace6b2d40>

INFO:lightrag:Load KV full_docs with 1 data
INFO:lightrag:Load KV text_chunks with 1 data
INFO:lightrag:Load KV llm_response_cache with 41 data
INFO:lightrag:Loaded graph from ./dickens/graph_chunk_entity_relation.graphml with 18 nodes, 11 edges
INFO:nano-vectordb:Load (18, 384) data
INFO:nano-vectordb:Init {'embedding_dim': 384, 'metric': 'cosine', 'storage_file': './dickens/vdb_entities.json'} 18 data
INFO:nano-vectordb:Load (11, 384) data
INFO:nano-vectordb:Init {'embedding_dim': 384, 'metric': 'cosine', 'storage_file': './dickens/vdb_relationships.json'} 11 data
INFO:nano-vectordb:Load (43, 384) data
INFO:nano-vectordb:Init {'embedding_dim': 384, 'metric': 'cosine', 'storage_file': './dickens/vdb_chunks.json'} 43 data
INFO:lightrag:Creating a new event loop in a sub-thread.
WARNING:lightrag:All docs are already in the storage
INFO:lightrag:Writing graph with 18 nodes, 11 edges
INFO:lightrag:Creating a new event loop in a sub-thread.
Traceback (most recent call last):
  File "/home/horanchen/ydy/study/code/LightRAG/examples/lightrag_hf_demo.py", line 39, in <module>
    rag.query("What are the top themes in this story?", param=QueryParam(mode="naive"))
  File "/home/horanchen/ydy/study/code/LightRAG/lightrag/lightrag.py", line 244, in query
    return loop.run_until_complete(self.aquery(query, param))
  File "/home/horanchen/anaconda3/envs/lightrag/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/horanchen/ydy/study/code/LightRAG/lightrag/lightrag.py", line 278, in aquery
    response = await naive_query(
  File "/home/horanchen/ydy/study/code/LightRAG/lightrag/operate.py", line 1052, in naive_query
    maybe_trun_chunks = truncate_list_by_token_size(
  File "/home/horanchen/ydy/study/code/LightRAG/lightrag/utils.py", line 172, in truncate_list_by_token_size
    tokens += len(encode_string_by_tiktoken(key(data)))
  File "/home/horanchen/ydy/study/code/LightRAG/lightrag/operate.py", line 1054, in <lambda>
    key=lambda x: x["content"],
TypeError: 'NoneType' object is not subscriptable

How can this be changed?

**Comment by TerraceCN** [comment]
Try deleting all files in the working directory, reconstructing the graph and vectors

**Comment by DayanaYuan** [comment]
> Try deleting all files in the working directory, reconstructing the graph and vectors

When I use all the contents of the book, it appears ''out of memory''. What parameter can be modified to make this error disappear without changing the data?

**Comment by TerraceCN** [comment]
> > Try deleting all files in the working directory, reconstructing the graph and vectors
> 
> When I use all the contents of the book, it appears ''out of memory''. What parameter can be modified to make this error disappear without changing the data?

Try lowering the following parameters:

- `embedding_batch_num`
- `embedding_func_max_async`
- `llm_model_max_token_size`
- `llm_model_max_async`

and `top_k` of `QueryParam`

**Comment by DayanaYuan** [comment]
> > > Try deleting all files in the working directory, reconstructing the graph and vectors
> > 
> > 
> > When I use all the contents of the book, it appears ''out of memory''. What parameter can be modified to make this error disappear without changing the data?
> 
> Try lowering the following parameters:
> 
> * `embedding_batch_num`
> * `embedding_func_max_async`
> * `llm_model_max_token_size`
> * `llm_model_max_async`
> 
> and `top_k` of `QueryParam`

''Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.''              Will this ''Default to no truncation'' make a difference?

**Comment by TerraceCN** [comment]
> ''Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.'' Will this ''Default to no truncation'' make a difference?

Based on my observations of the code, this could be potentially problematic.

The `sentence-transformers/all-MiniLM-L6-v2` model used in the sample only supports a maximum length of 512, whereas the default `chunk_token_size` is 1200, and the encode and decode operations on the tokens are performed using a gpt-40 tokenizer. tokenizer.I think this may cause the input text length to exceed the acceptable length of the model and lead to miscalculation of embedding or loss of information.

It is recommended that you replace the embedding model with a longer input length (e.g. bge-m3), or reduce the `chunk_token_size`.

**Comment by DayanaYuan** [comment]
> > ''Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.'' Will this ''Default to no truncation'' make a difference?
> 
> Based on my observations of the code, this could be potentially problematic.
> 
> The `sentence-transformers/all-MiniLM-L6-v2` model used in the sample only supports a maximum length of 512, whereas the default `chunk_token_size` is 1200, and the encode and decode operations on the tokens are performed using a gpt-40 tokenizer. tokenizer.I think this may cause the input text length to exceed the acceptable length of the model and lead to miscalculation of embedding or loss of information.
> 
> It is recommended that you replace the embedding model with a longer input length (e.g. bge-m3), or reduce the `chunk_token_size`.

The html knowledge graph is shown below, but this looks like a problem, what is the problem?
![Uploading 微信图片_20241023172715.png…]()

**Comment by DayanaYuan** [comment]
![Uploading 微信图片_20241023172715.png…]()

**Comment by Erickrus** [comment]
I get the same issue. Can you help? 


I use ollama:

```
NAME                     ID              SIZE      MODIFIED       
nomic-embed-text:v1.5    0a109f422b47    274 MB    52 minutes ago    
llama3.1:8b              42182419e950    4.7 GB    52 minutes ago    
```

I installed the package using pip.

I got this finally.

```
Traceback (most recent call last):
  File "/content/LightRAG/examples/lightrag_ollama_demo.py", line 29, in <module>
    rag.query("What are the top themes in this story?", param=QueryParam(mode="naive"))
  File "/content/LightRAG/lightrag/lightrag.py", line 244, in query
    return loop.run_until_complete(self.aquery(query, param))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/content/LightRAG/lightrag/lightrag.py", line 278, in aquery
    response = await naive_query(
  File "/content/LightRAG/lightrag/operate.py", line 1052, in naive_query
    maybe_trun_chunks = truncate_list_by_token_size(
  File "/content/LightRAG/lightrag/utils.py", line 172, in truncate_list_by_token_size
    tokens += len(encode_string_by_tiktoken(key(data)))
  File "/content/LightRAG/lightrag/operate.py", line 1054, in <lambda>
    key=lambda x: x["content"],
TypeError: 'NoneType' object is not subscriptable
```


looking at the output ./dickens/lightrag.log. No new entities and relationships found.
I use this settings for graphrag. But it's not working for lightrag this moment.
```
2024-10-23 09:13:17,910 - lightrag - INFO - Logger initialized for working directory: ./dickens
2024-10-23 09:13:17,910 - lightrag - DEBUG - LightRAG init with param:
  working_dir = ./dickens,
  chunk_token_size = 1200,
  chunk_overlap_token_size = 100,
  tiktoken_model_name = gpt-4o-mini,
  entity_extract_max_gleaning = 1,
  entity_summary_to_max_tokens = 500,
  node_embedding_algorithm = node2vec,
  node2vec_params = {'dimensions': 1536, 'num_walks': 10, 'walk_length': 40, 'window_size': 2, 'iterations': 3, 'random_seed': 3},
  embedding_func = {'embedding_dim': 768, 'max_token_size': 8192, 'func': <function <lambda> at 0xe248363fd90>},
  embedding_batch_num = 32,
  embedding_func_max_async = 16,
  llm_model_func = <function ollama_model_complete at 0xe23dfdd2440>,
  llm_model_name = llama3.1:8b,
  llm_model_max_token_size = 32768,
  llm_model_max_async = 16,
  key_string_value_json_storage_cls = <class 'lightrag.storage.JsonKVStorage'>,
  vector_db_storage_cls = <class 'lightrag.storage.NanoVectorDBStorage'>,
  vector_db_storage_cls_kwargs = {},
  graph_storage_cls = <class 'lightrag.storage.NetworkXStorage'>,
  enable_llm_cache = True,
  addon_params = {},
  convert_response_to_json_func = <function convert_response_to_json at 0xe23dfdbfc70>

2024-10-23 09:13:17,911 - lightrag - INFO - Load KV full_docs with 0 data
2024-10-23 09:13:17,911 - lightrag - INFO - Load KV text_chunks with 0 data
2024-10-23 09:13:17,911 - lightrag - INFO - Load KV llm_response_cache with 0 data
2024-10-23 09:13:17,913 - lightrag - INFO - Creating a new event loop in a sub-thread.
2024-10-23 09:13:17,914 - lightrag - INFO - [New Docs] inserting 1 docs
2024-10-23 09:13:18,383 - lightrag - INFO - [New Chunks] inserting 42 chunks
2024-10-23 09:13:18,384 - lightrag - INFO - Inserting 42 vectors to chunks
2024-10-23 09:13:24,587 - lightrag - INFO - [Entity Extraction]...
2024-10-23 09:27:15,397 - lightrag - WARNING - Didn't extract any entities, maybe your LLM is not working
2024-10-23 09:27:15,397 - lightrag - WARNING - No new entities and relationships found
2024-10-23 09:27:15,403 - lightrag - INFO - Writing graph with 0 nodes, 0 edges
2024-10-23 09:27:15,441 - lightrag - INFO - Creating a new event loop in a sub-thread.
```

You can refer to this colab notebook.

https://github.com/Erickrus/llm/blob/main/lightrag_with_ollama.ipynb

**Comment by benx13** [comment]
experiencing the same issue using gpt-4o-mini and text-embeddings3-small. Requesting this issue to be reopened
